### PR TITLE
abspath.h file is generated by makeheaders tool

### PR DESCRIPTION
**Pull request by skrab-sah**
1. We don't need to commit the file.
2. Added routin for abspath.c in Makefile.
3. Added tool support for makeheaders.

cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Đoàn Trần Công Danh 
        <congdanhqx@gmail.com>

cc: Đoàn Trần Công Danh 
        <congdanhqx@gmail.com>

### CODE REVIEW

**Comment by skrab-sah** [comment]
I want suggestion here.
why win+VS build failed and how do i fix it.

**Comment by skrab-sah** [comment]
> ```
> Not to repeat earlier feedback
> ```
sorry, reopen pull request option was not available.

**Comment by skrab-sah** [comment]
> ```
> I think this really goes to what i was pointing out in
> https://lore.kernel.org/git/220923.861qs25yr8.gmgdl@evledraar.gmail.com/
> ```

Yes, you are right.

> ```
> You're making very fundimental changes to a subsystem that your changes
> themselves show you clearly don't understand that well.

> Firstly, we have a lot of things in this makefile which don't require C
> compilation, so putting a "hdr" as an "all" dependency is a no-go.
> ```
yes it needed to be done just before creating object file, not as an dependency of "all".

> ```
> Secondly, you've globally marked our Makefile as "nothing here can run
> in parallel", i.e. the single biggest slowdown it's ever had, presumably
> because you got some dependency chain wrong, and are usin git as a
> workaround.
> ```
I needed help here.
In GNU make it runs perfectly in parallel mode (without .NOTPARALLEL:) but running in unix make, dependency chain goes wrong.

**Comment by dscho** [comment]
> > ```
> > I think this really goes to what i was pointing out in
> > https://lore.kernel.org/git/220923.861qs25yr8.gmgdl@evledraar.gmail.com/
> > ```
> 
> Yes.
> 
> > ```
> > You're making very fundimental changes to a subsystem that your changes
> > themselves show you clearly don't understand that well.
> > 
> > Firstly, we have a lot of things in this makefile which don't require C
> > compilation, so putting a "hdr" as an "all" dependency is a no-go.
> > ```
> 
> Yes, it needed to be done just before creating object file, not as an dependency of "all".
> 
> > ```
> > Secondly, you've globally marked our Makefile as "nothing here can run
> > in parallel", i.e. the single biggest slowdown it's ever had, presumably
> > because you got some dependency chain wrong, and are usin git as a
> > workaround.
> > ```
> 
> The main problem is here, and I needed help here. In GNU make it runs perfectly in parallel mode (without .NOTPARALLEL:) but running in unix make, dependency chain goes wrong.

Unfortunately, this message did not reach the intended recipient. You will need to follow the guidance at https://github.com/gitgitgadget/gitgitgadget/wiki/ReplyToThis to reply to https://lore.kernel.org/git/221012.86r0zdmmq1.gmgdl@evledraar.gmail.com (as hinted at the top of https://github.com/git/git/pull/1353#issuecomment-1275847459).

**Pull request closed without merging**
