### PR TITLE
Typo: dot after sentence

### PR DESCRIPTION
**Pull request by hginzel**

### CODE REVIEW

**Comment by dscho** [comment]
@hginzel are you still interested in submitting this patch series?

**Review by ryujinxx — APPROVED** [review]

**Comment by dscho** [comment]
> 
> 
> @hginzel are you still interested in submitting this patch series? (You will need to rebase this, in order to drop the merge commit, but other than that, this PR should be good to go.)

@hginzel I assume the answer is "no"...

**Comment by dscho** [comment]
I'll just close it. It's always possible, and quick, to reopen.

**Pull request closed without merging**
