### PR TITLE
Update git rebase documentation to clarify HEAD behavior

### PR DESCRIPTION
**Pull request by lalunamel**
The first few paragraphs in the git-rebase.txt documentation lay out the steps git takes during a rebase:
1. everything from `<upstream>..HEAD` is saved to a temporary area
2. `HEAD` is set to `<upstream>`
3. the changes held in the temporary area are applied one by one in order on top of the new `HEAD`

The second step was described using the phrase `The current branch is reset to <upstream>`, which is true (because `HEAD` == current branch), but not clear.

### CODE REVIEW

**Comment by submitgit** [comment]
@lalunamel sent this commit (https://github.com/git/git/compare/659889482ac63411daea38b2c3d127842ea04e4d...6aef46308f48155b43a30764d651e980ca18384f) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/010201580457bdd2-99237b54-5e36-4430-bb8d-7e9088aed522-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=010201580457bdd2-99237b54-5e36-4430-bb8d-7e9088aed522-000000@eu-west-1.amazonses.com) [](010201580457bdd2-99237b54-5e36-4430-bb8d-7e9088aed522-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@lalunamel are you still interested in this PR? If not, please close. Otherwise I will suggest how to proceed from here.

**Comment by lalunamel** [comment]
Oh yeah - I totally gave up on this after I learned the PR process for the git repo is more complex than "click the merge button"

**Comment by dscho** [comment]
😞

**Pull request closed without merging**
