### PR TITLE
Solving 2 Error documentations

### PR DESCRIPTION
**Pull request by NishantJoshi00**
This is to solve the problem with the errors where the documentation was not properly followed.

### CODE REVIEW

**Comment by dscho** [comment]
This is probably too large a patch to be sent to the mailing list, and it breaks the tests, too...

**Comment by NishantJoshi00** [comment]
Yes it did, I was actually working on a script that replaces all the error messages and make them documentation friendly, I used regex, there might have been some faults along the way, does the tests provide me with where the errors might have occoured

**Comment by NishantJoshi00** [comment]
> Yes it did, I was actually working on a script that replaces all the error messages and make them documentation friendly, I used regex, there might have been some faults along the way, does the tests provide me with where the errors might have occoured

I just found what caused the error, how can I run these tests locally on my own, git fork

**Comment by dscho** [comment]
Here is a helpful document: https://github.com/git-for-windows/git/wiki/Running-Git's-regression-tests

**Review by gitster — COMMENTED** [review]
Thanks for trying to help improve our documentation.

I think the author of this commit misunderstands what the "Do not *BEGIN* with capital" rule about die/error messages is about. It refers *ONLY* to the fact that unlike ordinary English sentence, where we begin a sentence with a capital letter, these messages do not capitalize the first letter only because it is at the beginning of the sentence.

So, if a word, even the one that happens to be at the beginning of die/warning message, has other reason to be spelled in capital letters, that is not something we want to downcase. As an example, changes to die("BUG") are unwelcome. Also, I see references to HEAD that are not even at the beginning of the message are butchered, but these changes are unwarranted.

But many other changes are exactly the kind of fixes we would appreciate. "cannot do X" should not begin with "C", for example.

It is entirely possible that the documentation guideline document *is* misleading and needs to be improved to avoid the misunderstanding that led to the undesirable changes in this commit, and perhaps that is worth fixing separately.

Thanks.

**Comment by NishantJoshi00** [comment]
Ok, cool I got it, i will do those changes to my script, and test it locally, thanks so much for your insight

**Comment by gitster** [comment]
Note that a "patch generated by script" is generally frowned upon, as the time spent running a script and sending the results out without proof-reading is far less expensive than the reviewer time on the list, which is the most scarce resource that is shared among community members. In addition, touching files that have otherwise some real activity on would put extra burden on the maintainer.

**Pull request closed without merging**
