### PR TITLE
Reuse formatting logic from ref-filter in cat-file

### PR DESCRIPTION
**Pull request by telezhnaya**
The main idea of the patch is to get rid of using custom formatting in
cat-file and start using general one from ref-filter.
Additional bonus is that cat-file becomes to support many new
formatting commands like %(if), %(color), %(committername) etc.

### CODE REVIEW

**Comment by submitgit** [comment]
@telezhnaya sent these 24 commits (https://github.com/git/git/compare/5be1f00a9a701532232f57958efab4be8c959a29...ee870f21caa0da0692bc8b693f3bbb64be39200e) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016133ff3a86-44d354ec-13c6-4c38-bc75-1ba4422db5a7-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016133ff3a86-44d354ec-13c6-4c38-bc75-1ba4422db5a7-000000@eu-west-1.amazonses.com) [](0102016133ff3a86-44d354ec-13c6-4c38-bc75-1ba4422db5a7-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@telezhnaya sent these 25 commits (https://github.com/git/git/compare/5be1f00a9a701532232f57958efab4be8c959a29...476ce9631bfcfcb14a006a6ae5f5d87fbb3701c9) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016165b8b3c4-54efe4c4-6d19-435d-b5b9-6c727771353b-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016165b8b3c4-54efe4c4-6d19-435d-b5b9-6c727771353b-000000@eu-west-1.amazonses.com) [](0102016165b8b3c4-54efe4c4-6d19-435d-b5b9-6c727771353b-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@telezhnaya sent these 23 commits (https://github.com/git/git/compare/5be1f00a9a701532232f57958efab4be8c959a29...0fe95679b3e245b52ae06c9134ad620047eff418) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020161890f4236-47989eb4-c19f-4282-9084-9d4f90c2ebeb-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020161890f4236-47989eb4-c19f-4282-9084-9d4f90c2ebeb-000000@eu-west-1.amazonses.com) [](01020161890f4236-47989eb4-c19f-4282-9084-9d4f90c2ebeb-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@telezhnaya was this PR merged via 55574bd04ada? Or is there still pending work in here?

**Comment by dscho** [comment]
> was this PR merged via [55574bd](https://github.com/git/git/commit/55574bd04ada4dab255dad687665ee7578bc6a32)?

Still wondering...

**Comment by telezhnaya** [comment]
@dscho No, it wasn't

**Pull request closed without merging**
