### PR TITLE
For git-p4, .gitconfig file should be explicitly mentioned for perforce settings

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by dscho** [comment]
Please make sure that your commit message focuses on answering the question "why?" more than on "how?", and that it wraps at <= 76 columns per line. Also do make sure to add your [sign off](https://git-scm.com/docs/SubmittingPatches#dco).

Finally send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
@paul-hammant gentle ping?

**Comment by paul-hammant** [comment]
Sure, I'll redo.

**Comment by dscho** [comment]
> Sure, I'll redo.

Great!

Seeing as you deleted the original fork from which this PR was made (and hence have *no* chance of updating the commit), I'll close this PR.

**Pull request closed without merging**
