### PR TITLE
userdiff.c: Added support for record types in C#

### PR DESCRIPTION
**Pull request by 304NotModified**
Support for C# 9 records. See https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/records

I will try to use [gitgitgadget](https://gitgitgadget.github.io/)

cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>

### CODE REVIEW

**Comment by 304NotModified** [comment]
> There is an issue in commit [d85bd1b](https://github.com/git/git/commit/d85bd1bc7e5be65a5136cef06ba93801054b60c7):
> Commit checks stopped - the message is too short

This should be fixed (force pushed)

**Comment by dscho** [comment]
> Prefixed commit message must be in lower case: userdiff.c: Added support for record types in C#.

It's the "A" of "Added" that GitGitGadget wants to be lower-case.

**Comment by dscho** [comment]
Also, please note that the Git project prefers the commit message to be in the imperative tense: "Add support for C# record types".

**Comment by 304NotModified** [comment]
> Also, please note that the Git project prefers the commit message to be in the imperative tense: "Add support for C# record types".

Thanks, fixed

**Comment by 304NotModified** [comment]
@dscho any idea when I could expect a response?

**Comment by dscho** [comment]
It was a bit busy a time, what with feature freeze for v2.31.0. Maybe reply on the Git mailing list with a gentle ping?

**Review by ryujinxx — APPROVED** [review]

**Comment by dscho** [comment]
@304NotModified I think you will need to ping the list again.

**Comment by 304NotModified** [comment]
I think I gonna give up...

**Pull request closed without merging**
