### PR TITLE
Read Contributing

### PR DESCRIPTION
**Pull request by bnhassin**
Automated Building Docker Hub

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by bnhassin** [comment]
Referenced #534 to assignee @bnhassin comments

**Comment by bnhassin** [comment]
git fetch origin
git checkout -b bnhassin-patch-1 origin/bnhassin-patch-1
git merge contribute
[https://github.com/bnhassin/git/blame/1f954aa6e2b49c9de728ed5633316002e9c9dd76/emergency](url)

>

**Comment by dscho** [comment]
@bnhassin is this a legit PR you really want to have accepted by the Git project? If so, what is its purpose? That is really unclear from this PR's description as well as from its commit messages.

**Comment by dscho** [comment]
> @bnhassin is this a legit PR you really want to have accepted by the Git project? If so, what is its purpose? That is really unclear from this PR's description as well as from its commit messages.

@bnhassin I am still interested in getting some answers.

**Comment by bnhassin** [comment]
> > @bnhassin is this a legit PR you really want to have accepted by the Git project? If so, what is its purpose? That is really unclear from this PR's description as well as from its commit messages.
> 
> @bnhassin I am still interested in getting some answers.

@dscho  The "PR" Git repository waiting for established on Azure DevOps and Visual Studio App-Centre

**Comment by bnhassin** [comment]
Recent build attachment in real time
Screenshot_20190612-203800

**Comment by bnhassin** [comment]
> Recent build attachment in real time
> Screenshot_20190612-203800

Url from the file changed▶https://github.com/git/git/blob/049b7b311127fed8355a258b81814158f2701430/SSH

**Comment by dscho** [comment]
> The "PR" Git repository waiting for established on Azure DevOps and Visual Studio App-Centre

And what exactly is that supposed to mean? I don't understand.

**Comment by dscho** [comment]
@bnhassin this is not a PR that you ever intend for the Git project to integrate, right? If so, it would be good to simply close it.

**Comment by bnhassin** [comment]
> @bnhassin this is not a PR that you ever intend for the Git project to integrate, right? If so, it would be good to simply close it.

Yes that's right, the'is branch from PR and if need access for merging

**Pull request closed without merging**
