### PR TITLE
Add dirty sync revision into git-p4

### PR DESCRIPTION
**Pull request by blabla-p4-sync**

### CODE REVIEW

**Comment by Amikarimi** [comment]
9b968d1

**Comment by dscho** [comment]
@blabla-p4-sync if you are still interested in this, please provide a [good commit message](https://git-scm.com/docs/SubmittingPatches#describe-changes), [sign off](https://git-scm.com/docs/SubmittingPatches#dco) on the change, and send it to the Git mailing list for review.

**Comment by dscho** [comment]
@blabla-p4-sync ping?

**Comment by dscho** [comment]
@blabla-p4-sync ping?

**Comment by dscho** [comment]
@blabla-p4-sync @blabla-p4 gentle ping?

**Comment by dscho** [comment]
@blabla-p4-sync gentle ping again?

If you are no longer interested in this PR, why not close it? It serves nobody to let it sit dead in the water.

**Comment by dscho** [comment]
@blabla-p4-sync another gentle ping?

**Comment by dscho** [comment]
@blabla-p4-sync ping...

**Comment by dscho** [comment]
> @blabla-p4-sync if you are still interested in this

Apparently not.

**Pull request closed without merging**
