### PR TITLE
third_txt

### PR DESCRIPTION
**Pull request by Issaga221**
ajout third.txt

### CODE REVIEW

**Comment by Issaga221** [comment]
fourth.txt

**Comment by Issaga221** [comment]
> git ajouter

removing third.txt

**Comment by Issaga221** [comment]
git log

**Comment by Issaga221** [comment]
core.pager=cat

**Comment by Issaga221** [comment]
git config --global

**Comment by kalawarie** [comment]
> git config --global

**Comment by dscho** [comment]
@Issaga221 @kalawarie Please use your own fork for practicing how to use GitHub.

**Pull request closed without merging**
