### PR TITLE
ci: replace our Azure Pipeline by GitHub Actions

### PR DESCRIPTION
**Pull request by dscho**
Our Azure Pipeline has served us well over the course of the past year or so, steadily catching issues before the respective patches hit the `next` branch.

There is a GitHub-native CI system now, though, called ["GitHub Actions"](https://github.com/features/actions) which is essentially on par with Azure Pipelines as far as our needs are concerned, and it brings a couple of advantages:

- It is substantially easier to set up than Azure Pipelines: all you need is to add the YAML-based build definition, push to your fork on GitHub, and that's it.
- The syntax is a bit easier to read than Azure Pipelines'.
- We get more concurrent jobs (Azure Pipelines is limited to 10 concurrent jobs).

With this change, users also no longer need to open a PR at https://github.com/git/git or at https://github.com/gitgitgadget/git _just_ to get the benefit of a CI build. They just push to their fork on GitHub and monitor the build. Easier than making apple pie.

The only caveat is that this will only work once the patch series makes it to `master`. In the meantime, you can adore the CI build here: https://github.com/dscho/git/actions/runs/67349068

### CODE REVIEW

**Comment by sgn** [comment]
Hi @dscho,

I've rebase your series on top of `dd/musl-libc-travis-ci`.

The result is published here: https://github.com/sgn/git/tree/js/ci-swap-azure-pipelines-with-github-actions

**Comment by dscho** [comment]
@sgn great! Do you want to take custody of the patches and submit v2? I'm a bit time-constrained today and might not be able to take care of that until tomorrow or even later...

**Comment by sgn** [comment]
On 2020-03-31 23:24:51-0700, Johannes Schindelin <notifications@github.com> wrote:
> @sgn great! Do you want to take custody of the patches and submit
> v2? I'm a bit time-constrained today and might not be able to take
> care of that until tomorrow or even later...

I'm working on it.

Anyway, the current code doesn't report failure when linux32 job is
failing.

GitHub Action also allows run directly inside container.

I will change to run linux32 and linux-musl directly inside container.

-- 
Danh

**Comment by dscho** [comment]
Thank you so much, @sgn !

**Comment by dscho** [comment]
Thank you _so_ much @sgn !

**Pull request closed without merging**
