### PR TITLE
doc: fixed a typo in git-submodule.txt

### PR DESCRIPTION
**Pull request by elonderin**
fixed a typo in the  doc of submodule

### CODE REVIEW

**Comment by elonderin** [comment]
ok, seems like i need to pimp this a bit before it's ready for merge

**Comment by elonderin** [comment]
just pimped the commit message according to tutorial

**Comment by dscho** [comment]
> Error: Could not determine full name of elonderin

@elonderin sorry about that. There is a ticket about this: https://github.com/gitgitgadget/gitgitgadget/issues/153. Nobody got around to implementing that yet, though...

**Comment by elonderin** [comment]
i guess this is now good to go

/submit

**Pull request closed without merging**
