### PR TITLE
Fixed typo in readme

### PR DESCRIPTION
**Pull request by nirgeier**

### CODE REVIEW

**Comment by megaxlr** [comment]
you shouldn't be opening pull requests here.

"Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements."

**Comment by dscho** [comment]
This typo seems to be still in Git's source code. Please send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
@nirgeier gentle ping?

**Comment by nirgeier** [comment]
will get to it later on this week

**Comment by dscho** [comment]
@nirgeier gentle ping?

**Comment by dscho** [comment]
@nirgeier another gentle ping? (You would need to use `git rebase` to get rid of the merge commit... but then you can easily open a PR at https://github.com/gitgitgadget/git and submit the patches to the Git mailing list in a convenient way.)

**Comment by dscho** [comment]
@nirgeier another gentle ping?

**Comment by dscho** [comment]
@nirgeier another gentle ping? (You would still need to use `git rebase` to get rid of the merge commit... but then you can easily open a PR at https://github.com/gitgitgadget/git and submit the patches to the Git mailing list in a convenient way.)

**Comment by dscho** [comment]
@nirgeier surprisingly, this typo is still there: https://github.com/git/git/blob/pu/Documentation/RelNotes/2.11.0.txt

Now, you can force me to keep pinging you, or you can follow my suggestion, rebase, force-push and submit already...

**Comment by nirgeier** [comment]
PR added:

https://github.com/gitgitgadget/git/pull/469

**Comment by nirgeier** [comment]
https://github.com/gitgitgadget/git/pull/469
ᐧ

**Comment by dscho** [comment]
Let's continue the conversation over there, then.

**Pull request closed without merging**
