### PR TITLE
Master #5 pushed to latest: https://github.com/git/git/pull/677

### PR DESCRIPTION
**Pull request by bnhassin**
Packager Master:
https://hub.docker.com/repository/registry-1.docker.io/bnhassin/git/builds/ce553c89-d4d8-497d-9e99-be8d70ec378f

### CODE REVIEW

**Comment by bnhassin** [comment]
> # Welcome to [GitGitGadget](https://gitgitgadget.github.io/)
> Hi @bnhassin, and welcome to GitGitGadget, the GitHub App to send patch series to the Git mailing list from GitHub Pull Requests.
> 
> Please make sure that this Pull Request has a good description, as it will be used as cover letter.
> 
> Also, it is a good idea to review the commit messages one last time, as the Git project expects them in a quite specific form:
> 
> * the lines should not exceed 76 columns,
> * the first line should be like a header and typically start with a prefix like "tests:" or "commit:", and
> * the commit messages' body should be describing the "why?" of the change.
> * Finally, the commit messages should end in a [Signed-off-by:](https://git-scm.com/docs/SubmittingPatches#dco) line matching the commits' author.
> 
> It is in general a good idea to await the automated test ("Checks") in this Pull Request before contributing the patches, e.g. to avoid trivial issues such as unportable code.
> 
> ## Contributing the patches
> Before you can contribute the patches, your GitHub username needs to be added to the list of permitted users. Any already-permitted user can do that, by adding a comment to your PR of the form `/allow`. A good way to find other contributors is to locate recent pull requests where someone has been `/allow`ed:
> 
> * [Search: is:pr is:open "/allow"](https://github.com/gitgitgadget/git/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%22%2Fallow%22)
> 
> Both the person who commented `/allow` and the PR author are able to `/allow` you.
> 
> An alternative is the channel [`#git-devel`](https://webchat.freenode.net/#git-devel) on the FreeNode IRC network:
> 
> ```
> <newcontributor> I've just created my first PR, could someone please /allow me? https://github.com/gitgitgadget/git/pull/12345
> <veteran> newcontributor: it is done
> <newcontributor> thanks!
> ```
> 
> Once on the list of permitted usernames, you can contribute the patches to the Git mailing list by adding a PR comment `/submit`.
> 
> After you submit, GitGitGadget will respond with another comment that contains the link to the cover letter mail in the Git mailing list archive. Please make sure to monitor the discussion in that thread and to address comments and suggestions.
> 
> If you want to see what email(s) would be sent for a submit request, add a PR comment `/preview` to have the email(s) sent to you. You must have a public GitHub email address for this.
> 
> If you do not want to subscribe to the Git mailing list just to be able to respond to a mail, you can download the mbox ("raw") file corresponding to the mail you want to reply to from the Git mailing list. If you use GMail, you can upload that raw mbox file via:
> 
> ```shell
> curl -g --user "<EMailAddress>:<Password>" --url "imaps://imap.gmail.com/INBOX" -T /path/to/raw.txt
> ```
> 
> ## Need help?
> New contributors who want advice are encouraged to join [git-mentoring@googlegroups.com](https://groups.google.com/forum/#!forum/git-mentoring), where volunteers who regularly contribute to Git are willing to answer newbie questions, give advice, or otherwise provide mentoring to interested contributors. You must join in order to post or view messages, but anyone can join.
> 
> You may also be able to find help in real time in the developer IRC channel, [`#git-devel`](https://webchat.freenode.net/#git-devel) on Freenode. Remember that IRC does not support offline messaging, so if you send someone a private message and log out, they cannot respond to you. The scrollback of `#git-devel` is [archived](https://colabti.org/irclogger//irclogger_logs/git-devel), though.

https://github.com/git/git/pull/677

**Comment by bnhassin** [comment]
Add feedback reviewing: https://github.com/git/git/pull/677

Le dimanche 8 décembre 2019, Noômen Ben Hassin <notifications@github.com> a
écrit :

**Comment by dscho** [comment]
This is, again, not meant for contribution to Git.

@bnhassin how about staging such PRs in your personal fork rather than in git/git?

**Comment by dscho** [comment]
@bnhassin this started being annoying a long time ago. Do please consider using your own fork to play these games instead of the official GitHub mirror of the official Git project.

**Pull request closed without merging**
