### PR TITLE
Typo fix in githooks.txt: removed extra comma

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
It's not needed in that sentence.

Signed-off-by: Josh Goldberg <me@joshuakgoldberg.com>

### CODE REVIEW

**Comment by dscho** [comment]
Looks correct, but it needs a [sign off](https://git-scm.com/docs/SubmittingPatches#dco).

After that, please use [submitGit](https://submitgit.herokuapp.com), [GitGitGadget](https://gitgitgadget.github.io) to submit the patch, or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
Hrm. @rtyley any ideas?

**Comment by dscho** [comment]
> Re submitGit:
> 
> image
> 
> > Application error

I think this has been resolved in the meantime.

**Comment by dscho** [comment]
> New changes since you last viewed
>
> Merge branch 'master' into patch-1 

Would you mind rebasing to `master` (thereby dropping the merge commit that cannot be sent as a patch)?

**Comment by JoshuaKGoldberg** [comment]
This change has been a bit of a pain and the submitGit site still crashes for me. You can go ahead and take it separately if you'd like.

**Comment by rtyley** [comment]
> This change has been a bit of a pain and the submitGit site still crashes for me. You can go ahead and take it separately if you'd like.

The crashes seem to be due to the Heroku servers (aka 'dynos') taking a long time to warm up - you can usually get the thing to work by just hitting refresh a few times. This seems to have recently become a more noticeable problem...

**Comment by dscho** [comment]
> You can go ahead and take it separately

Unfortunately, I already spend more time than is reasonable trying to help contributors get their patches in, so no, I cannot go ahead and take it separately (I am not maintainer of this project, otherwise I might be tempted to cherry-pick). Sorry.

**Pull request closed without merging**
