### PR TITLE
Turn fetch_if_missing into field of struct repository

### PR DESCRIPTION
**Pull request by dev-shubham1**
Hi GIT contributors !
I am Shubham Ghule.I have resolved the problem of extern integer fetch_if_missing by putting it in the structure repository as a field.Made the relevent changes suggested by @dscho.
I'm looking forward to your review.
Special thanks to @dscho.
with regards,
Shubham.

### CODE REVIEW

**Comment by dscho** [comment]
Welcome, and thanks for working on this!

It seems that there are quite a few merge conflicts, would you mind rebasing this to the current `master`?

Please make sure that your commit message focuses on answering the question "why?" more than on "how?", and that it wraps at <= 76 columns per line. Also do make sure to add your [sign off](https://git-scm.com/docs/SubmittingPatches#sign-off) with a valid email address.

> changed fetch_if_missing from global to struct repo

There is a strong preference for using the "imperative mood", please do use it in your commit messages. In general, you should find inspiration how to improve the commit messages here: https://git-scm.com/docs/SubmittingPatches#describe-changes

Finally send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
Whoa, now I am confused.

I just realized that you opened a GitGitGadget PR at https://github.com/gitgitgadget/git/pull/351, then closed it, only to open a PR here.

But the Git project does not accept PRs. Only patch submissions via the Git mailing list. GitGitGadget owes its existence to the mission to help convert PRs to such submissions, so it is not at all clear why the _GitGitGadget_ PR was closed, _in favor_ of a Git PR (which will never be accepted).

What's up with that, @dev-shubham1?

**Comment by dscho** [comment]
@dev-shubham1 gentle ping?

**Comment by dscho** [comment]
It actually looks as if the Git project pursues a different direction: getting rid of those assignments altogether (as they are not thread-safe). See e.g. https://github.com/git/git/commit/fce9e836d395fb315bb8b77619868098a6cb02eb

**Comment by dscho** [comment]
@dev-shubham1 are you interested in this PR at all anymore?

**Comment by dev-shubham1** [comment]
> @dev-shubham1 are you interested in this PR at all anymore?
On it.Can you elaborate what I have to do further ?

**Comment by dscho** [comment]
> Can you elaborate what I have to do further ?

Imitate https://github.com/git/git/commit/fce9e836d395fb315bb8b77619868098a6cb02eb, i.e. getting rid of `fetch_if_missing` assignments altogether (and instead using `OBJECT_INFO_SKIP_FETCH_OBJECT`)

**Comment by dscho** [comment]
@dev-shubham1 gentle ping?

**Comment by dev-shubham1** [comment]
> @dev-shubham1 gentle ping?

working on it.Submitting by 9th feb 2020

**Comment by dev-shubham1** [comment]
> @dev-shubham1 gentle ping?

got rid of all fetch_if_missing assignments successfully.What next ?

**Comment by dscho** [comment]
> got rid of fetch_if_missing assignments as suggested.What next ?

Force-push?

**Comment by dev-shubham1** [comment]
> Imitate [fce9e83](https://github.com/git/git/commit/fce9e836d395fb315bb8b77619868098a6cb02eb), i.e. getting rid of `fetch_if_missing` assignments altogether (and instead using `OBJECT_INFO_SKIP_FETCH_OBJECT`)

OBJECT_INFO_SKIP_FETCH_OBJECT is also a global variable but the initial aim was to reduce global variables right ?

**Comment by dscho** [comment]
> OBJECT_INFO_SKIP_FETCH_OBJECT is also a global variable

No, it is a constant. The idea is that it is used in a `flag` that is passed down through the call path that needs it. See e.g. https://github.com/git/git/commit/e362fadcd03753471cf8e7fc91d6d721b7423b8f#diff-92b149d6fe7eece2bd0ff0fb1ed33a6fR65-R66. 

Note: the `OBJECT_INFO_*` constants are all powers of two so that they can be combined. See e.g. https://github.com/git/git/commit/6462d5eb9a5b23ab9cff4e3c92ff930600562d8f#diff-7891df559f581cdcc9168363e0f932a1R676-R677

**Comment by dscho** [comment]
Shall we close this in favor of https://github.com/gitgitgadget/git/pull/606?

**Comment by dev-shubham1** [comment]
Ya Sure

**Pull request closed without merging**
