### PR TITLE
Certifica-se -> Certifique-se

### PR DESCRIPTION
**Pull request by miguelleitao**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
@miguelleitao thank you for your contribution!

I would lie if I said that I speak even one word Portuguese, so I cannot say whether your fix is correct or not, but what I *can* say is that Git's translations are managed at https://github.com/git-l10n/git-po. Could you please open a PR there? Thank you!

**Comment by dscho** [comment]
> Could you please open a PR there?

@miguelleitao please still do that. Thanks.

**Comment by miguelleitao** [comment]
thank you @dscho. I already submited a PR there. It was closed and I've been redirected to another forked repo.   It is now open and waiting...

**Comment by dscho** [comment]
Thank you!

**Pull request closed without merging**
