### PR TITLE
Fix Spanish translation issues

### PR DESCRIPTION
**Pull request by dsevilla**
I fixed several issues with the Spanish translation:
- Many constructions were in passive voice, not common in Spanish
- In some parts, "commit" was used (widely used in Spanish), and in other parts "confirmación" was used. I wrote all of them as "commit", as it is the de facto standard for "commit" even in Spanish (I yet have to see anybody calling "confirmación" to commit)

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by DJm00n** [comment]
According to [po/TEAMS](https://github.com/git/git/blob/master/po/TEAMS) file you should write about translation issues to Spanish team coordinator: Christopher Díaz <christopher.diaz.riv@gmail.com> (@ChrisADR) and/or resubmit your pull request to his https://github.com/ChrisADR/git-po repository.

**Comment by ChrisADR** [comment]
Thanks @DJm00n and thank you @dsevilla for taking time to fix typos, please resubmit your pull request to https://github.com/ChrisADR/git-po/tree/2.15-next branch. I'm working there some fixes. You can either send it as PR or email.

Thanks again

**Comment by ChrisADR** [comment]
Closing since commits were merged in ChrisADR/git-po. Thank you all

**Comment by DJm00n** [comment]
@ChrisADR no I can't. Only repo admin or pull author (@dsevilla) can close this pull request.

**Comment by dsevilla** [comment]
Sorry to arrive this late, but were the changes actually merged in git-po?

**Comment by ChrisADR** [comment]
@dsevilla no, they were not. You had to submit your changes in ChrisADR/git-po repo, some of the changes in your commit were already fixed by other commits, other may need to be reviewed. Send to 'next' branch:

https://github.com/ChrisADR/git-po/tree/next

**Comment by dscho** [comment]
@dsevilla please rebase your branch (this should take care of dropping the already-fixed issues), and then open a PR either in the indicated fork or in https://github.com/git-l10n/git-po.

**Comment by dscho** [comment]
I will close this PR here, as indicated earlier.

**Pull request closed without merging**
