### PR TITLE
Fix typo (In such these cases -> In such cases)

### PR DESCRIPTION
**Pull request by ReneNyffenegger**
I believe, the changed sentence should read "In such cases..." rather than "In such these cases..."

### CODE REVIEW

**Comment by SHwareSystemsDev** [comment]
Alternate text, to me more accurate as a singular case that may happen frequently, as explained after, than as plural cases. Also fixes 'his' being typo of 'this' in original sentence.
-	you have. In such these cases, you do not make a new <<def_merge,merge>>
 	<<def_commit,commit>> but instead just update to his
 	revision.
+	you have. For this case you do not need to make a new <<def_merge,merge>> and
 	<<def_commit,commit>> as 2 steps. Instead you can just update to this
 	revision as one operation.

**Comment by gemini61888** [comment]
View email in web browser
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f1547fb5a6a06e9ab66bf37fea52fb45b0b4ea9fab706c77a14>

<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15e27bdb54d03057f59d6dfafc04e3cde4af278c6ea8ce0ca9>

<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15f461d4363bdcd58c2b2348a1cd5ba26baeb8715a4becd5af>

<http://click.mail-rushcard.com/?qs=b9b9f376813a6f152dfb48de498ffe30eebe6a3ada1733f95c1476f9de71d9dd>

<http://click.mail-rushcard.com/?qs=b9b9f376813a6f153eff2c6e1d75eaece37ae6dfed134372cff6888e3644751c>

| RushCard -Load Money
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f155083ac15269a15ac80964b5a990f7d0db1a753b9eee2f931>
Refer-a-Friend
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15adc18af1a8c7ce275942be51864c65635bdcda8d4c1ea0cf>Download
App
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f151bfd8d2211e63a5816667bec1c97f563b2ab3b0ec36ca053>Online
Account
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15adc18af1a8c7ce275942be51864c65635bdcda8d4c1ea0cf>
CASH
CHECKS IN A SNAP Have a check? Our mobile app1 allows you to use your
smartphone to cash checks anytime, anywhere, simply by snapping a pic on
your phone.2
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15d85212f4a0a61104881ccdf726e3e20e0d22b8854c16a4a9>
TRY
THE RUSHCARD MOBILE APP1
Get it now
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15d85212f4a0a61104881ccdf726e3e20e0d22b8854c16a4a9>
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15d85212f4a0a61104881ccdf726e3e20e0d22b8854c16a4a9>

<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15f81a41011fcff492af65cc09788ea44d2f0660a00433efbb>
START
CASHING CHECKS
WITH YOUR PHONE2
Watch the video
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15f81a41011fcff492af65cc09788ea44d2f0660a00433efbb>
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15f81a41011fcff492af65cc09788ea44d2f0660a00433efbb>


rushcard.com
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15fbb572025d42399c487d25b4ee9f0562fe73c9c587119ebe>

Customer Care
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15fa8aec9b364a16ad9b40bd66021168ec7c7e69c3e9f4b608>

Privacy Policies
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f154f054fb24471ce5f847809529cb59ef5e5d550d70c95b97c>

Website/App Privacy
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15fc119c04d59637078bbdf056e080ecea539bee2e27b225ad>

Text/Email Alerts
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15adc18af1a8c7ce275942be51864c65635bdcda8d4c1ea0cf>

Edit Profile
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15adc18af1a8c7ce275942be51864c65635bdcda8d4c1ea0cf>

1 Standard text message and data rates, fees, and charges may apply.

2 The Ingo Money service is provided by Ingo Money, Inc. and First Century
Bank, N.A. Use of Ingo Money is subject to Ingo Money and First Century
Bank Terms & Conditions, and the information you send is subject to
approval for funding in Ingo Money's sole discretion. Approved printed
payroll and government checks can be funded to your card in minutes for a
fee of 1% of the check value. All other check types may be funded in
minutes for 4% of check value. There is a minimum fee of $5 for all checks
approved and funded in minutes. Funds from approved checks may be loaded in
10 days at no charge provided the check does not return unpaid in the
10-day period. Unapproved checks will not be loaded to your card. Ingo
Money reserves the right to recover the funds from bad checks if you knew
the check was bad when you submitted it. If you attempt to cash or deposit
it elsewhere after funding or if you otherwise act illegally or
fraudulently. Fees may apply for loading or use of your card. Contact your
card issuer for details.

This advertising message was sent to: gemini61888@gmail.com. Please take a
moment to add email@mail-rushcard.com to your address book. You are
receiving this e-mail because you provided your e-mail address to RushCard.
To unsubscribe, click here
<http://click.mail-rushcard.com/?qs=b9b9f376813a6f15af0ac1540ac6b2a2a926f455a974212014ebc2d449e1e7f6>
and
allow up to seven days for your e-mail address to be removed. Please do not
reply to this e-mail as we are unable to respond to messages sent to this
address.

To contact RushCard Member Services, please call 866-787-4227, e-mail
agent@rushcard.com or write us at: RushCard Member Services, P. O. Box
42482, Cincinnati, OH 45242.

The Prepaid Visa RushCard is issued by MetaBank® pursuant to a license from
Visa U.S.A. Inc. and may be used everywhere Visa debit cards are accepted.
MetaBank; Member FDIC.

Copyright © 2016 UniRush, LLC. All Rights Reserved.

**Comment by gemini61888** [comment]
Reply to

**Comment by dscho** [comment]
This PR was applied as 2e39a246071eb7bc9153e48e0c9416f069ac2a17

**Pull request closed without merging**
