### PR TITLE
doc: remove extra quotes in generated docs

### PR DESCRIPTION
**Pull request by spectral54**
cc: Jeff King <peff@peff.net>
cc: Patrick Steinhardt <ps@pks.im>

### CODE REVIEW

**Comment by spectral54** [comment]
Updated the description to be what I thought I was sending.

/submit

**Comment by dscho** [comment]
> Updated the description to be what I thought I was sending.
> 
> /submit

@spectral54 the `/submit` command needs to be the entire content of the comment, otherwise GitGitGadget will ignore it.

**Pull request closed without merging**
