### PR TITLE
git-p4: speed up search for branch parent

### PR DESCRIPTION
**Pull request by jkuebart**
In this iteration, I have added more context and measurements to the commit message.

I have also made small improvements to the code suggested by reviewers.

I enhanced `t9801-git-p4-branch.sh` to test for the functionality, namely that branches are branched off at the correct point in their parents' history.

Signed-off-by: Joachim Kuebart <joachim.kuebart@gmail.com>

cc: Joachim Kuebart <joachim.kuebart@gmail.com>

cc: Luke Diamand <luke@diamand.org>
cc: Joachim Kuebart <joachim.kuebart@gmail.com>

### CODE REVIEW

**Comment by keerati808080** [comment]
t

ในวันที่ พฤ. 29 เม.ย. 2021 09:24 น. gitgitgadget-git[bot] <
***@***.***> เขียนว่า:

> On the Git mailing list
> ***@***.***>, Junio C Hamano
> wrote (reply to this
> <https://github.com/gitgitgadget/gitgitgadget/wiki/ReplyToThis>):
>

**Comment by jkuebart** [comment]
Hi @dscho, is there anything I can do to kick off CI again? I modified one of the tests and would like to ensure they pass before submitting to the list.

**Comment by dscho** [comment]
thanks for the ping, I kicked it off.

**Comment by jkuebart** [comment]
> thanks for the ping, I kicked it off.

unfortunately, due to a syntax error I'm going to require yet another run…

**Comment by dscho** [comment]
> 
> 
> > thanks for the ping, I kicked it off.
> 
> unfortunately, due to a syntax error I'm going to require yet another run…

Sorry for the delay...

**Pull request closed without merging**
