### PR TITLE
fix git-add.txt typo, add )

### PR DESCRIPTION
**Pull request by adispring**

### CODE REVIEW

**Comment by nxazli81no** [comment]
Yes
Pada 2017 6 5 17:27, "wangzengdi" <notifications@github.com> menulis:

**Comment by stefanbeller** [comment]
We do not use Github for development, though.

https://git.kernel.org/pub/scm/git/git.git/plain/Documentation/SubmittingPatches
https://git.kernel.org/pub/scm/git/git.git/plain/MaintNotes?h=todo

**Comment by dscho** [comment]
Do you still want to send the patch to the mailing list for review? You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by adispring** [comment]
thanks for reminding me. Yes, I will do that later.

**Comment by adispring** [comment]
> Do you still want to send the patch to the mailing list for review? You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

Sorry, I do not have time to make a pr for this, Can you make a pr?

**Comment by dscho** [comment]
> I do not have time to make a pr for this, Can you make a pr?

Okay, so let me take a deep breath before I react to this.

*breathes erratically*

No, I cannot make that PR for you. I already spend more time per day than the vast majority of Git contributors on working on Git, and now I even try to help contributors like you. My offer was to assist you. Not to take on even more responsibility than I already have, thank you.

**Comment by dscho** [comment]
Of course, you would also have to add your [sign off](https://git-scm.com/docs/SubmittingPatches#dco), so even if I *wanted* to take away work from you, I could not, as that sign-off is kind of a legal commitment *you* make, and I would not even be allowed to make that for you if I wished to do so.

**Comment by adispring** [comment]
> Of course, you would also have to add your [sign off](https://git-scm.com/docs/SubmittingPatches#dco), so even if I _wanted_ to take away work from you, I could not, as that sign-off is kind of a legal commitment _you_ make, and I would not even be allowed to make that for you if I wished to do so.

Ok, thanks for your explanation, I'll figure out how to make a pr to `git` in the correct way.

**Comment by dscho** [comment]
> I'll figure out how to make a pr to `git` in the correct way.

I hoped that @stefanbeller's and my hints would give you all the information you need :-(

To summarize: you need to
- rebase the patch on top of current `master`,
- make sure that you have a good commit message (in your case, `docs(add): fix typo` is probably all you need),
- [sign off](https://git-scm.com/docs/SubmittingPatches#dco) on your patch (by adding a `Signed-off-by:` line to the commit message), and
- send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

You might find GitGitGadget the most convenient, in which case you will have to open a new PR at https://github.com/gitgitgadget/git (and you will probably want to close this here PR at that that time). GitGitGadget should then greet you with a welcome message and an explanation how things will proceed from there.

**Comment by adispring** [comment]
@dscho , I've found that @jnavila has fixed this typo 5 months ago: https://github.com/git/git/commit/ba170517be039a04b1914ebe9b492d4139c707df#diff-1b7f268a8ebce07155d3e50aca600396R61

**Comment by jnavila** [comment]
@adispring Please close this PR. The change is already included.

**Comment by dscho** [comment]
> I've found that @jnavila has fixed this typo 5 months ago

Good! So it is time to close this PR. Please do so.

**Pull request closed without merging**
