### PR TITLE
Format

### PR DESCRIPTION
**Pull request by telezhnaya**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by submitgit** [comment]
@telezhnaya sent these 20 commits (https://github.com/git/git/compare/35ee755a8c43bcb3c2786522d423f006c23d32df...88d51ebfe9c8f04e5107807096a29efc4c126ef4) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016915f499b8-5813fc52-230b-469e-b939-a1244e83a2b9-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016915f499b8-5813fc52-230b-469e-b939-a1244e83a2b9-000000@eu-west-1.amazonses.com) [](0102016915f499b8-5813fc52-230b-469e-b939-a1244e83a2b9-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@telezhnaya is this PR still relevant?

**Comment by telezhnaya** [comment]
@dscho I hope I will return to it one day, but I am too busy right now, so I can't give any predictions. I guess you want me to close it for now and re-open when it would be ready.

**Comment by dscho** [comment]
> I guess you want me to close it for now and re-open when it would be ready.

Oh no, sorry, that was not my intention! I would have suggested to close it only if it has been applied.

**Comment by telezhnaya** [comment]
> > I guess you want me to close it for now and re-open when it would be ready.
> 
> Oh no, sorry, that was not my intention! I would have suggested to close it only if it has been applied.

Please do not worry :-) Everything is OK. Anyway, I need to change many pieces in this patch and send 2-3 additional small patches before I will re-send this one.

**Pull request closed without merging**
