### PR TITLE
submodule--helper: fix initialization of warn_if_uninitialized

### PR DESCRIPTION
**Pull request by orgads**
cc: Glen Choo <chooglen@google.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
Though for later iterations, v2, v3, etc, it is recommended to use the PR description to explain what has changed since the last iteration, see https://git-scm.com/docs/MyFirstContribution#responding-ggg

**Comment by phil-blain** [comment]
@dscho any idea why this PR does not have a `master` label, even though the branch was merged to `master`?

**Comment by dscho** [comment]
> @dscho any idea why this PR does not have a `master` label, even though the branch was merged to `master`?

Honestly, I have no idea... GitGitGadget probably has the wrong idea of the tip commit. When that happens, I kind of hope for the original contributors to notice and close the PR manually.

@orgads can this be closed?

**Comment by orgads** [comment]
Sure, thanks.

**Pull request closed without merging**
