### PR TITLE
make hg-to-git compatible with python2.x and 3.x

### PR DESCRIPTION
**Pull request by 4383**
Hi!

## Overview
- Improve compatibility with python2.x and python3.x for hg-to-git script.
- Apply language syntax compatible version.
- Fix PEP08 errors
- Fix pylint errors

### CODE REVIEW

**Comment by submitgit** [comment]
@4383 sent this commit (https://github.com/git/git/compare/b2e45c695d09f6a31ce09347ae0a5d2cdfe9dd4e...af6d857bf7578de168947db4f1cccedc7fb56fd7) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020161992fe7ce-b41bf370-1480-4efe-8980-0c52fb9b9be5-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020161992fe7ce-b41bf370-1480-4efe-8980-0c52fb9b9be5-000000@eu-west-1.amazonses.com) [](01020161992fe7ce-b41bf370-1480-4efe-8980-0c52fb9b9be5-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@4383 sent this commit (https://github.com/git/git/compare/a4ee44448fe98dcd8f1db9e43729ac67fc80e031...cbe71494f79a73b80b7d37682e55e78a755bbca5) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020161b421939a-4ad52aaa-dda8-4250-9bce-71f0ede1a199-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020161b421939a-4ad52aaa-dda8-4250-9bce-71f0ede1a199-000000@eu-west-1.amazonses.com) [](01020161b421939a-4ad52aaa-dda8-4250-9bce-71f0ede1a199-000000@eu-west-1.amazonses.com)

**Comment by estevanearmando** [comment]
Exelent

**Comment by dscho** [comment]
@4383 Junio replied in https://public-inbox.org/git/xmqqwoz7324d.fsf@gitster-ct.c.googlers.com/#t and in https://public-inbox.org/git/xmqqsh9v31wa.fsf@gitster-ct.c.googlers.com/. Maybe you want to answer?

**Comment by 4383** [comment]
@dscho thanks, I will take a look ASAP

**Comment by dscho** [comment]
@4383 gentle ping?

**Comment by 4383** [comment]
Hey @dscho 

Sorry I'm a little bit busy the last weeks, I'll try to take a look before the end of the week.

**Comment by dscho** [comment]
@4383 gentle ping?

**Comment by dscho** [comment]
> gentle ping?

Sorry, I should have been more clear: I see that https://public-inbox.org/git/xmqqsh9v31wa.fsf@gitster-ct.c.googlers.com/ is still unanswered on the mailing list...

And since you pushed a newer iteration of the patch (which looks pretty good, BTW!), maybe you want to use @submitgit once more to send it to the Git mailing list?

**Comment by submitgit** [comment]
@4383 sent this commit (https://github.com/git/git/compare/8dca754b1e874719a732bc9ab7b0e14b21b1bc10...6a9b17b29df4cada4cbd100fa69363b13d261487) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016d3f74d202-d5b32dd4-0098-4ad0-8ac7-5fde254f7796-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016d3f74d202-d5b32dd4-0098-4ad0-8ac7-5fde254f7796-000000@eu-west-1.amazonses.com) [](0102016d3f74d202-d5b32dd4-0098-4ad0-8ac7-5fde254f7796-000000@eu-west-1.amazonses.com)

**Comment by 4383** [comment]
@dscho thanks for the reminder, I already used the submitgit in July but I forgotten to validate the testing email, so no update on the mailing list in July.

I just submit the mail to the ML please confirm that's good for you.

Thanks

**Comment by dscho** [comment]
> I just submit the mail to the ML please confirm that's good for you.

Oh, it is good for me, all I wanted was for your work not to be done in vain... ;-)

**Comment by submitgit** [comment]
@4383 sent this commit (https://github.com/git/git/compare/8a3a6817e24ae1cf1fd08fb90b4a99e6817f646d...d7cc788f5eb0e78b77540618572011d110967e2f) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016d43812db5-722fe301-48f7-4b46-93e4-67dc2992629a-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016d43812db5-722fe301-48f7-4b46-93e4-67dc2992629a-000000@eu-west-1.amazonses.com) [](0102016d43812db5-722fe301-48f7-4b46-93e4-67dc2992629a-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@4383 sent this commit (https://github.com/git/git/compare/8a3a6817e24ae1cf1fd08fb90b4a99e6817f646d...c75582789dae064967cfcde8f8a42613c9f992ec) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016d45842c54-616d4b1c-3410-4237-9da8-708c5b0daabd-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016d45842c54-616d4b1c-3410-4237-9da8-708c5b0daabd-000000@eu-west-1.amazonses.com) [](0102016d45842c54-616d4b1c-3410-4237-9da8-708c5b0daabd-000000@eu-west-1.amazonses.com)

**Pull request closed without merging**
