### PR TITLE
DEVEL - Seraphire/p4 python (for CI testing)

### PR DESCRIPTION
**Pull request by seraphire**
This pull request is held in draft to allow a workspace for running the CI unit tests.
------------------------------------------------------------------------------------------
Issue: The current git-p4.py script does not work with python3.

I have attempted to use the P4 integration built into GIT and I was unable to get the program to run because I have Python 3.8 installed on my computer. I was able to get the program to run when I downgraded my python to version 2.7. However, python 2 is reaching its end of life.

Submission:
I am submitting a patch for the git-p4.py script that partially supports python 3.8.
This code was able to pass the basic tests (t9800) when run against Python3. This provides basic functionality.

In an attempt to pass the t9822 P4 path-encoding test, a new parameter for git P4 Clone was introduced.

--encoding Format-identifier

This will create the GIT repository following the current functionality; however, before importing the files from P4, it will set the git-p4.pathEncoding option so any files or paths that are encoded with non-ASCII/non-UTF-8 formats will import correctly.

Technical details:
The script was updated by futurize (https://python-future.org/futurize.html) to support Py2/Py3 syntax. The few references to classes in future were reworked so that future would not be required.
The existing code test for Unicode support was extended to normalize the classes “unicode” and “bytes” to across platforms:

‘unicode’ is an alias for ‘str’ in Py3 and is the unicode class in Py2.
‘bytes’ is bytes in Py3 and an alias for ‘str’ in Py2.
New coercion methods were written for both Python2 and Python3:

as_string(text) – In Python3, this encodes a bytes object as a UTF-8 encoded Unicode string.
as_bytes(text) – In Python3, this decodes a Unicode string to an array of bytes.
In Python2, these functions do not change the data since a ‘str’ object function in both roles as strings and byte arrays. This reduces the potential impact on backward compatibility with Python 2.

to_unicode(text) – ensures that the supplied data is encoded as a UTF-8 string. This function will encode data in both Python2 and Python3.
path_as_string(path) – This function is an extension function that honors the option “git-p4.pathEncoding” to convert a set of bytes or characters to UTF-8. If the str/bytes cannot decode as ASCII, it will use the encodeWithUTF8() method to convert the custom encoded bytes to Unicode in UTF-8.
Generally speaking, information in the script is converted to Unicode as early as possible and converted back to a byte array just before passing to external programs or files. The exception to this rule is P4 Repository file paths.

Paths are not converted but left as “bytes” so the original file path encoding can be preserved. This formatting is required for commands that interact with the P4 file path. When the file path is used by GIT, it is converted with encodeWithUTF8().

Signed-off-by: Ben Keene seraphire@gmail.com

### CODE REVIEW

**Comment by dscho** [comment]
> Thanks for taking the time to contribute to Git! Please be advised that the
> Git community does not use github.com for their contributions. Instead, we use
> a mailing list ([git@vger.kernel.org](mailto:git@vger.kernel.org)) for code submissions, code reviews, and
> bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
> to conveniently send your Pull Requests commits to our mailing list.
> 
> Please read the "guidelines for contributing" linked above!

@seraphire please replace this placeholder text by a meaningful description of this PR.

**Comment by seraphire** [comment]
On 12/3/2019 4:50 PM, Johannes Schindelin wrote:
>
>     Thanks for taking the time to contribute to Git! Please be advised
>     that the
>     Git community does not use github.com for their contributions.
>     Instead, we use
>     a mailing list (git@vger.kernel.org <mailto:git@vger.kernel.org>)
>     for code submissions, code reviews, and
>     bug reports. Nevertheless, you can use GitGitGadget
>     (https://gitgitgadget.github.io/)
>     to conveniently send your Pull Requests commits to our mailing list.
>
>     Please read the "guidelines for contributing" linked above!
>
> @seraphire <https://github.com/seraphire> please replace this 
> placeholder text by a meaningful description of this PR.
>
I'm working on building up this PR and have it set to "DRAFT". Will this 
be a problem?

**Comment by dscho** [comment]
> I'm working on building up this PR and have it set to "DRAFT". Will this be a problem?

No, but it would be nicer if you already had at least a rudimentary description what this is all about. In the least, please do demonstrate that you understand the purpose of the placeholder text in the description and delete it.

**Comment by dscho** [comment]
> it would be nice to have someone to show you what this is! Or better yet explain how to use it for your life!

This is probably an unintentional, off-topic comment. @seraphire please ignore.

**Comment by dscho** [comment]
@seraphire what's the status on this one?

**Comment by seraphire** [comment]
As Yang has taken the front on this, and I've not had time available. I'm closing this as I won't be able to do more work on porting to Py3 in the near term.

**Comment by dscho** [comment]
Thank you for clarifying, and of course for your work!

**Pull request closed without merging**
