### PR TITLE
Update gitignore.txt

### PR DESCRIPTION
**Pull request by minhtaile2712**
Fix typo

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
@minhtaile2712 welcome to the Git project!

As to your contribution, it is not really clear to me whether the change is correct or not. Would you mind following the guidance in https://github.blog/2022-06-30-write-better-commits-build-better-projects/ to write a good commit message that explains the context and your intent? That will make it much easier for any reviewer to understand enough to assess whether this patch should be applied. Thank you!

**Comment by dscho** [comment]
@minhtaile2712 ping?

**Comment by minhtaile2712** [comment]
@dscho I was being busy for a few days. I will update this as you said today.

**Comment by Gautami-2607** [comment]
Hello @gitgitgadget-git 
As I am new to open-source projects so, could you please assign this issue to me?

**Comment by dscho** [comment]
> Hello @gitgitgadget-git As I am new to open-source projects so, could you please assign this issue to me?

That's not how things work over here. @minhtaile2712 said they would come back to work on this a bit more.

Besides, this is Open Source, nobody assigns anyone to do anything, it's volunteer-based.

If you want to contribute to Git @Gautami-2607 I encourage you to first look at a couple of contributions, reviews and discussions over at https://lore.kernel.org/git/, to see how things are run in the Git project. Once you're comfortable working on something, just do it. For inspiration, you can use https://github.com/gitgitgadget/git/issues/, or just think of an enhancement to Git that you personally would like to see come about. Then, contribute (in a new PR).

**Comment by dscho** [comment]
There was a comment left by @gitster [directly at the commit](https://github.com/git/git/commit/552a968c097c530f1f368ac5c385a1acc2e7f463#commitcomment-87551758) (that I am sure was meant friendlier than it sounds):

> Trailing slash is not a typo. It limits the match only to directory, and removing it will invalidate what the next line says (i.e. it matches a/frotz directory).
>
> IOW, this change is wrong.

**Comment by dscho** [comment]
@minhtaile2712 care to clarify why this is closed?

**Comment by minhtaile2712** [comment]
@dscho I checked my commit today. I think I was wrong about something when I created this. I think @gitster is right.

**Pull request closed without merging**
