### PR TITLE
Update http.cookieFile with in-memory cookie processing

### PR DESCRIPTION
**Pull request by pszlazak**
cc: Jeff King <peff@peff.net>
cc: brian m. carlson <sandals@crustytoothpaste.net>
cc: Junio C Hamano <gitster@pobox.com>
cc: Piotr Szlazak <piotr.szlazak@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
@pszlazak please follow the guidance in https://github.blog/2022-06-30-write-better-commits-build-better-projects/ to improve it, in particular with a strong focus on this part:

  | What you’re doing | Why you’re doing it
-- | -- | --
High-level (strategic) | **Intent** (what does this accomplish?) | **Context** (why does the code do what it does now?)
Low-level (tactical) | **Implementation** (what did you do to accomplish your goal?) | **Justification** (why is this change being made?)

Also, could you please add a `Signed-off-by` line (using your real name) and in your author information? The Git project [insists on that](https://git-scm.com/docs/SubmittingPatches#dco). You can fix it by configuring `user.name`, then `git commit --amend --reset-author --signoff` (deleting the superseded `Signed-off-by` line), and force-pushing.

**Comment by pszlazak** [comment]
Hello @dscho!  
I updated my commit message. I hope it now meets commiting rules of Git project.

**Comment by dscho** [comment]
> Hello @dscho! I updated my commit message. I hope it now meets commiting rules of Git project.

@pszlazak looks good to me. `/submit` time!

**Comment by pszlazak** [comment]
Hello @dscho!  
Change proposed in this PR was delivered via 8d201195515a6b4decc0df435c8fbff93d855a5c. Is there any special command for gitgitgadget to close PR?

**Comment by dscho** [comment]
> Hello @dscho! Change proposed in this PR was delivered via [8d20119](https://github.com/git/git/commit/8d201195515a6b4decc0df435c8fbff93d855a5c). Is there any special command for gitgitgadget to close PR?

@pszlazak oh well, GitGitGadget should have noticed that it was integrated already and closed the PR. I'll do that manually now. Thanks for the ping!

**Pull request closed without merging**
