### PR TITLE
git-p4: Fix bug with encoding of P4 client name

### PR DESCRIPTION
**Pull request by cohomology**
CC: Tao Klerks <tao@klerks.biz>

### CODE REVIEW

**Comment by cohomology** [comment]
@TaoK:
@DJm00n : 

Can you allow me?

**Comment by SpaldingGreene** [comment]
PR #1285- Client name is- Bradley Lee green

**Comment by cohomology** [comment]
Sorry, I was in vacation. I tried to refactor the coding a bit, I hope it is more clear now. Not sure about the camel- vs. underscore naming convention in git-p4.py

**Comment by cohomology** [comment]
Actually I do not know how to clean up my mess. My original commit contained two different email addresses of mine, which was correctly complained by Junio. The only possiblity was a force commit which is not allowed either ;-). I also lost my original commit which can only be seen in the github user interface but can't be checked out. I now try to do an additional commit of a cherry-pick taken from the seen branch.

**Pull request closed without merging**
