### PR TITLE
Git

### PR DESCRIPTION
**Pull request by Bhanditz**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by Carbon-Zero** [comment]
LOL!!!!  This is the most insane thing I have ever heard of!!  The Git community doesn't use Git?  Would anybody care to enlighten me a to why this is?  It's so counterintuitive.  Is it just to maintain absolute control over the source?  This is the code to manage the code.  It makes absolutely no sense to use the archaic processes you have invented.

**Comment by ezequielgarcia** [comment]
> LOL!!!! This is the most insane thing I have ever heard of!! The Git community doesn't use Git?

The comments says, "...the Git community does not use github".

**Comment by Carbon-Zero** [comment]
LOL! The eighties called and they want their process of using a mailing list for commits back!!  ROTFLMFAO!!!!

**Review by lorenzochavez1992outlook-afk — COMMENTED** [review]
[]()

**Pull request merged**
