### PR TITLE
Cleaned up and refactored some of the code to make it a little bit more readable

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
Comments purged in favor of better function calls. Comment moved from function to header file. Header file inclusion moved to top.

### CODE REVIEW

**Comment by rumpelsepp** [comment]
I don't want to blame you, but this pr most likely will not be accepted, see here: https://raw.githubusercontent.com/git/git/master/Documentation/SubmittingPatches

**Comment by lgp36018** [comment]
merge file for projects

**Comment by lgp36018** [comment]
typo error

**Comment by gitster** [comment]
Seeing no activity after previous comments; I'll close this. If interested please polish and send them to git@vger.kernel.org

Thanks.

**Pull request closed without merging**
