### PR TITLE
Start preparing merge-related tests to work with multiple merge backends

### PR DESCRIPTION
**Pull request by newren**
This series starts preparing the merge related tests to work with multiple backends: merge-recursive or merge-ort.  Further work will be coming.

Changes since v2:
  * fix typos pointed out by Eric
  * reworded another commit message for clarify

The greater flexibility patches at the end of the series also previews some of the design changes being brought by merge-ort.

Merges cleanly with next and seen, despite the pile of testcase renames.

### CODE REVIEW

**Comment by newren** [comment]
libgit2 must have some issue with its rename detection; there are no conflicts with this branch and master, nor even with next or seen.  All merge automatically and cleanly at the command line.

**Comment by newren** [comment]
gitgitgadget: you idiot bot, it does merge cleanly.  It's just libgit2 has broken rename detection or something like that making GitHub think it doesn't merge cleanly.

grumble, grumble...

**Comment by newren** [comment]
The osx-clang failures look like infra failures to me; a bunch of git-p4 test failures which is highly suspect given that I didn't modify any product code -- I only modified tests, and none of the git-p4 ones.  So I'm going to ignore that one.

**Comment by andyzimmerer** [comment]
Cool

**Pull request closed without merging**
