### PR TITLE
Add --default to git config

### PR DESCRIPTION
**Pull request by nhsoukai**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by submitgit** [comment]
@nhsoukai sent these 5 commits (https://github.com/git/git/compare/4123bcaed0897cad152c052a5fa4e499e4dafcf4...25688a8223f85eb1d18f20f55c5458def778c994) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015fb0bf2f74-cb456171-fe65-4d83-8784-b553c7c9e584-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015fb0bf2f74-cb456171-fe65-4d83-8784-b553c7c9e584-000000@eu-west-1.amazonses.com) [](0102015fb0bf2f74-cb456171-fe65-4d83-8784-b553c7c9e584-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@nhsoukai sent this commit (https://github.com/git/git/compare/5f9953d2c365bffed6f9ee0c6966556bd4d7e2f4...635bdb1aa78fc25da44ad80732a1f693b0d89aee) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016004959a28-410f021b-ac2b-4756-8e55-244071c074b5-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016004959a28-410f021b-ac2b-4756-8e55-244071c074b5-000000@eu-west-1.amazonses.com) [](0102016004959a28-410f021b-ac2b-4756-8e55-244071c074b5-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@nhsoukai is it possible that this PR was essentially superseded by the `tb/config-default` patches, merged via 00bb99c424e9? I.e. does https://github.com/git/git/compare/00bb99c424e9^...00bb99c424e9^2 look like what you wanted?

**Comment by nhsoukai** [comment]
That looks indeed similar.

**Comment by dscho** [comment]
> That looks indeed similar.

Okay, let's close this PR, then ;-)

**Comment by dscho** [comment]
TBH I am rather convinced that the truth of the matter is that @peff felt that this should still be implemented and talked @ttaylorr into implementing it ;-)

**Comment by peff** [comment]
>  I am rather convinced that the truth of the matter is that @peff felt that this should still be implemented and talked @ttaylorr into implementing it

That is true. But it may also be true that I talked @nhsoukai into working on it, too. :wink:

@ttaylorr's series was [based on](https://public-inbox.org/git/20180306022052.GA46077@syl.local/) the earlier work here. Thanks both of you for indulging my `git config` desires (and to @dscho for cleaning up old PRs here).

**Comment by dscho** [comment]
> @ttaylorr's series was [based on](https://public-inbox.org/git/20180306022052.GA46077@syl.local/) the earlier work here.

Thanks for filling in that blank!

**Pull request closed without merging**
