### PR TITLE
docs: Fix sentencing

### PR DESCRIPTION
**Pull request by TheKhanj**
Just fixed a sentence in docs.

### CODE REVIEW

**Review by ANGGBELPAS — COMMENTED** [review]
> docs: Fix sentencing #1485

**Comment by dscho** [comment]
> sentencing

@TheKhanj please note that this verb means [something different](https://www.oxfordlearnersdictionaries.com/definition/english/sentence_2) than what is meant here.

Please review commit messages in [the history of this file](https://github.com/git/git/commits/708448d8abaf5e24b90bee5bcc23fac3a0ea2538/Documentation/revisions.txt); You will find that they are expected to have a certain format which you will want to imitate.

Also, please note that your [Sign-off is required](https://git-scm.com/docs/SubmittingPatches#dco).

Other than that: good find!

**Comment by TheKhanj** [comment]
I've applied your advices.
- [x] sign off my patch
- [x] change commit message to follow project's guideline

**Comment by dscho** [comment]
@TheKhanj you will still need to `/submit`, as explained [here](https://github.com/git/git/pull/1485#issuecomment-1493142852).

**Comment by TheKhanj** [comment]
I'm gonna close this pull request then.

**Pull request closed without merging**
