### PR TITLE
GIT TO DA CHOPPA!

### PR DESCRIPTION
**Pull request by dvorontsov**
:)

### CODE REVIEW

**Comment by shrayasr** [comment]
:+1: Must ship!

**Comment by gitster** [comment]
;-)

**Comment by dvorontsov** [comment]
I need your memory, your compiler, and your processor!

**Comment by shubhamchaudhary** [comment]
:zap: Btw any easter egg in git currently?

**Comment by gitster** [comment]
@shubhamchaudhary We used to have good ones until 8587ead78ad3d2af760270b21035ffe48fde3e7b

**Pull request closed without merging**
