### PR TITLE
docs: explain the order of output in The batched mode of git-cat-file(1)

### PR DESCRIPTION
**Pull request by ahmedakef**
this is the same change as https://github.com/git/git/pull/1761 but due to missteps, the PR got closed and I couldn't fix it,
also applied the review comments from @pks-t  
cc: Patrick Steinhardt [ps@pks.im](mailto:ps@pks.im)

### CODE REVIEW

**Comment by dscho** [comment]
> /submit

That may have been a bit premature. The [initial comment](https://github.com/git/git/pull/1768#issue-2477472302) (which is used as "cover letter" between the commit message and the diff) neither contains the now-missing information about the previous iteration (including the range-diff and a detailed list of changes you made since sending v1, along with an explanation why this is marked as another v1 instead of a v2), plus: it still contains the boilerplate template starting with "Thanks for taking the time to contribute to Git!" that you most likely wanted to avoid sending in your contribution.

**Comment by ahmedakef** [comment]
@dscho updated, thank you

**Comment by dscho** [comment]
> /submit

Okay, hold your horses. You don't want to send more than _one_ iteration of the patch in the same day, preferably even in a couple of days. This is now the third iteration in quick succession, which would make for a fine way to upset reviewers, if that was your goal.

Instead, reply on-list to your patch if you have additional things to say, and do _slow down_ with the frequency of sending new iterations.

**Pull request closed without merging**
