### PR TITLE
I fixed the style

### PR DESCRIPTION
**Pull request by Cis112233**
I had to. Please accept this. It caused me pain to look at the style

### CODE REVIEW

**Comment by Archcry** [comment]
I quote from the top of this git repo

"Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements."

**Comment by msoucy** [comment]
In no universe is this "fixed" source code. It breaks apart essential tokens like `->`, rendering the code actually nonfunctional and unable to build.

**Comment by wheelerlaw** [comment]
@Cis112233 This is the dumbest PR I have probably ever seen.

Why the fuck would you change:
```
static const char *read_var(const char *var)
```
to:
```
 static
 const char * read_var(const char *
     var)
```

If you think this is an acceptable coding style, do the rest of the developer world a favor and never touch a keyboard again.

**Comment by Cis112233** [comment]
AHEM. I may have just run this in the JS beautifier and broke it all

**Pull request closed without merging**
