### PR TITLE
Avoid multiple recursive calls for same path in read_directory_recursive()

### PR DESCRIPTION
**Pull request by newren**
This series provides some "modest" speedups (see commit message for patch 8), and should allow 'git status --ignored' to complete in a more reasonable timeframe for Martin Melka (see https://lore.kernel.org/git/CANt4O2L_DZnMqVxZzTBMvr=BTWqB6L0uyORkoN_yMHLmUX7yHw@mail.gmail.com/).  It also cleans up the fill_directory() code and API, and fixes bash-completion for 'git add untracked-dir/'.

Changes since v4:
  * cleanups suggested by Junio (patch 1)
  * new testcases that would have displayed multiple bugs with v4 (patch 2)
  * fixed the bugs with v4 (look for LEADING_PATHSPEC in patch 8)
  * fixed ANOTHER exponential slowdown codepath (look for MODE_MATCHING in patch 8)
  * make DIR_KEEP_UNTRACKED_CONTENTS less of a weird one-off (patch 9)
  * reduce number of calls to [do_]match_pathspec() (patch 10)
  * fix error-proneness of fill_directory() API (patch 11)
  * fix bash-completion results for 'git add' on an untracked dir (patch 12)

This is one of those rare patchsets that is absolutely perfect and risk-free.  That's right, bask in their glory and the ease of conscience from using such solid stuff.  Using this series will even innoculate you from bugs outside of dir.c, and ones external to git, and even bugs external to your computer.  It's just that good.  Pay no attention to the man behind the curtain, er, I mean the huge warnings in patch 8, er...I mean what warnings?  There's no warnings to view, this stuff is solid as can be.

But if an extra pair of eyes wants to look at commit message in patch 8, or at the new patches (2 and 9-12) and opine on how perfect everything looks and feels, be my guest.

Cc: Martin Melka <martin.melka@gmail.com>, SZEDER Gábor <szeder.dev@gmail.com>, Samuel Lijin <sxlijin@gmail.com>, Nguyễn Thái Ngọc Duy <pclouds@gmail.com>, Derrick Stolee <stolee@gmail.com>

### CODE REVIEW

**Comment by newren** [comment]
Not sure why TravisCI is showing as still pending; clicking through it shows that it has completed and is green so I'm going to submit...

**Comment by kamolsrisan** [comment]
good

**Pull request closed without merging**
