### PR TITLE
This PR enables a successful git build on z/OS.

### PR DESCRIPTION
**Pull request by HarithaIBM**
Introduced z/OS (OS/390) as a platform in config.mak.uname

cc: Haritha D <Harithamma.D@ibm.com>
cc: "Ghanshyam Thakkar" <shyamthakkar001@gmail.com>
cc: <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by HarithaIBM** [comment]
@dscho Hi Johannes, I need help. May i please know how do i proceed to get this PR reviewed? Thank you.

**Comment by dscho** [comment]
> `build: Support z/OS (OS/390).`
> Prefixed commit message must be in lower case

Please amend the commit message so that "support" starts with a lower-case "s", then force-push and `/submit`.

**Comment by HarithaIBM** [comment]
I have addressed comments from Junio. Squashed the commits.

**Comment by dscho** [comment]
@HarithaIBM please also remove the boiler plate from your initial comment on the PR; This will be sent as "cover letter" and the advice for new contributors is undesirable there.

**Pull request closed without merging**
