### PR TITLE
Fixing error on print statement

### PR DESCRIPTION
**Pull request by stunney**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by stunney** [comment]
bump

**Comment by dscho** [comment]
@stunney this patch *might* be good, but I, for one, am not informed enough about Perforce/Python issues to make the call.

What I *can* tell is that the commit message needs to be wrapped and signed off (see https://git-scm.com/docs/SubmittingPatches#describe-changes for details, even if it does not mention the <=76 columns/row wrapping that you will see in *every* commit in this repository).

Once you fix the commit message, you have the choice of either [GitGitGadget](https://gitgitgadget.github.io/) or [submitGit](https://submitgit.herokuapp.com/) to submit your patch to the Git mailing list for review. Or you can send it manually via `git send-email` (see https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch for some tips).

**Comment by dscho** [comment]
@stunney ping?

**Comment by dscho** [comment]
@stunney gentle ping?

**Comment by stunney** [comment]
I updated the title of the PR.  I also resolved the merge conflict.
This change has nothing to do with Perforce itself.  This is a Python runtime error for a standard print statement.

**Comment by stunney** [comment]
Also, this email based pull request thing seems overly complicated.  All I
want to do it fix a compiler error.  Can someone from the core team just
cherry-pick my change and check it into master/develop and just kill my
PR?  I'm really okay with that.

Stephen

**Comment by dscho** [comment]
Sadly, this PR is not in a state where it would be easy to take it off of your hands and upstream it. If you could _at least_ add your sign-off (as required by the Git project), rebase (so that there is no merge commit in your PR branch) and bring the commit message in line with the existing style (look at the commit history, and you will get the idea real quick), that would be helpful.

**Pull request closed without merging**
