### PR TITLE
Add shell completion for git remote rm

### PR DESCRIPTION
**Pull request by keith**
Previously git remote rm did not complete your list of removes as remove
does.

### CODE REVIEW

**Comment by submitgit** [comment]
@keith sent this commit (https://github.com/git/git/compare/29533fb16899725af9306e0c3b83da8954c0e48a...00461580e9f2cb4e3ce387f5519e2a9941c89185) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020160a0004473-277c3d7c-4e3b-4c50-9d44-4a106f37f1d9-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020160a0004473-277c3d7c-4e3b-4c50-9d44-4a106f37f1d9-000000@eu-west-1.amazonses.com) [](01020160a0004473-277c3d7c-4e3b-4c50-9d44-4a106f37f1d9-000000@eu-west-1.amazonses.com)

**Comment by takpare** [comment]
takpar

**Comment by keith** [comment]
Abandoning this because it appears the mailing list folks would prefer to remove `git remote rm` instead.

**Comment by taweesakteejantuk66** [comment]
thanks

**Pull request closed without merging**
