### PR TITLE
credential: load default config

### PR DESCRIPTION
**Pull request by koutcher**
Make `git credential fill` honour the core.askPass variable.

Signed-off-by: Thomas Koutcher <thomas.koutcher@online.fr>

cc: Jeff King <peff@peff.net>
cc: Thomas Koutcher <thomas.koutcher@online.fr>

### CODE REVIEW

**Review by ghost1986 — APPROVED** [review]
(invalid)

**Review by ghost1986 — COMMENTED** [review]
#883

**Review by kasunsewwandika — APPROVED** [review]

**Review by kasunsewwandika — APPROVED** [review]

**Pull request closed without merging**
