### PR TITLE
fix unclear and misleading comments in merge-recursive

### PR DESCRIPTION
**Pull request by newren**

### CODE REVIEW

**Comment by newren** [comment]
The test failure on osx-gcc is clearly not caused by any of my changes; my changes only tweaked comments, not actual code, and the comments I touched weren't in any python files to boot.  So I'm going to ignore that error and submit.

**Comment by ksajamalksieel** [comment]
P1

**Comment by atabaytebrizl** [comment]
6 Ağu 2020 Per 14:23 tarihinde Atabay Tebrizli <atabaytebrizli@gmail.com>
şunu yazdı:

**Comment by atabaytebrizl** [comment]
6 Ağu 2020 Per 01:42 tarihinde gitgitgadget-git[bot] <
notifications@github.com> şunu yazdı:

**Comment by atabaytebrizl** [comment]
2 Ağu 2020 Paz 06:52 tarihinde Elijah Newren <notifications@github.com>
şunu yazdı:

**Comment by atabaytebrizl** [comment]
6 Ağu 2020 Per 03:11 tarihinde gitgitgadget-git[bot] <
notifications@github.com> şunu yazdı:

**Comment by yufi1213** [comment]
#826

**Comment by yufi1213** [comment]
Ok

**Comment by yufi1213** [comment]
[Dokumen.docx](https://github.com/git/git/files/5046653/Dokumen.docx)

**Pull request closed without merging**
