### PR TITLE
credential-wincred doc: document the helper as a relay to Windows Credential Manager

### PR DESCRIPTION
**Pull request by smarkwell**
Documenting the purpose of git-credential-wincred

### CODE REVIEW

**Comment by dscho** [comment]
That is a good idea, but it should go into `contrib/credential/wincred/` and the `Makefile` in that subdirectory should build the documentation just like it is done in `contrib/subtree/` (see https://github.com/git/git/blob/v2.21.0/contrib/subtree/Makefile#L22-L36, https://github.com/git/git/blob/v2.21.0/contrib/subtree/Makefile#L48-L51, https://github.com/git/git/blob/v2.21.0/contrib/subtree/Makefile#L60-L64 and https://github.com/git/git/blob/v2.21.0/contrib/subtree/Makefile#L70-L89).

Once you did that, please rebase the patch and send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
@smarkwell gentle ping?

**Comment by dscho** [comment]
@smarkwell another gentle ping?

**Comment by smarkwell** [comment]
@dscho this is exceptionally low on my priority list (I opened this 4 years ago) and I won't be spending time to go through the described process.  If you wish to take the changes and apply them yourself, please do, and consider this message release of any ownership on my part.  Otherwise I can close this PR.

**Pull request closed without merging**
