### PR TITLE
Stopped sha v2

### PR DESCRIPTION
**Pull request by moy**
Test and fix a miss-call to post-rewrite hook in `git rebase -i -x`.

I wanted to wait a bit more before sending this v2, but I can't wait
to test this submitgit application in real ;-).

Change since v1: fix a broken &&-chain in test. Thanks Eric.

### CODE REVIEW

**Comment by moy** [comment]
I've sent this PR to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/0000014d7bc3f6bf-72bd5f07-9e26-411a-8484-e9b86a1bf429-000000@eu-west-1.amazonses.com) [](0000014d7bc3f6bf-72bd5f07-9e26-411a-8484-e9b86a1bf429-000000@eu-west-1.amazonses.com)

**Comment by gitster** [comment]
OK, now we know submitGit works (for some definition of working, I think it reversed the threading order, but hopefully the bug is fixed now ;-), care to close this entry?

**Comment by yiqiejieyoukeneng** [comment]
submitGit

**Comment by yiqiejieyoukeneng** [comment]
Gmane

**Pull request closed without merging**
