### PR TITLE
Bisect final

### PR DESCRIPTION
**Pull request by pranitbauva1997**

### CODE REVIEW

**Comment by submitgit** [comment]
@pranitbauva1997 sent these 27 commits (https://github.com/git/git/compare/2632c897f74b1cc9b5533f467da459b9ec725538...a71e28ab591c08c3215b66c15542a011fc2593f5) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/01020156b73fe5b4-5dc768ab-b73b-4a21-ab92-018e2a7aa6f7-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=01020156b73fe5b4-5dc768ab-b73b-4a21-ab92-018e2a7aa6f7-000000@eu-west-1.amazonses.com) [](01020156b73fe5b4-5dc768ab-b73b-4a21-ab92-018e2a7aa6f7-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@pranitbauva1997 sent these 27 commits (https://github.com/git/git/compare/3cdd5d19178a54d2e51b5098d43b57571241d0ab...3d3a3c05d76ff52b24484888e9f9676ad98150fc) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/01020157c38b19e0-81123fa5-5d9d-4f64-8f1b-ff336e83ebe4-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=01020157c38b19e0-81123fa5-5d9d-4f64-8f1b-ff336e83ebe4-000000@eu-west-1.amazonses.com) [](01020157c38b19e0-81123fa5-5d9d-4f64-8f1b-ff336e83ebe4-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@pranitbauva1997 are there maybe even more PRs that can be closed? 😄

**Comment by pranitbauva1997** [comment]
@dscho Thanks again! I will look and close them.

**Pull request closed without merging**
