### PR TITLE
Simplified merge logic

### PR DESCRIPTION
**Pull request by pi1024e**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

The logic for the merging is somewhat confusing. So I simplified it to be equivalent. I tested all my changes to ensure in practice they work.

The first thing I did was test out which branch would occur for every possible value of 

remoteheads->next | common->next | option_commit | Branch
-- | -- | -- | --
T | T | T | A
T | T | F | A
T | F | T | A
T | F | F | A
F | T | T | C
F | T | F | C
F | F | T | B
F | F | F | A

Using this truth table, I was able to deduce that if the second branch ran, the if statement for the first branch was false. Taking the inverse, it was then found many of the checks were redundant, so the if statement was rewritten to have each branch run under the same exact conditions, except each value is evaluated as little as possible.

I hope you can approve of this and show me how to send it.

Thank you.

### CODE REVIEW

**Comment by LifeIsStrange** [comment]
@pi1024e
Hi, my comment is totally off topic with your pull request, but do you think there's hope that Git fix it's merge algorithm ? 
https://anu.dev/documentation/associativity.html

**Comment by dscho** [comment]
@LifeIsStrange it's off topic all right. And a much better venue to discuss it would be [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently). You will find that you get the most useful feedback if you carefully craft a mail that contains all information necessary to understand your request, with links that do not _need_ to be followed to understand the context.

@pi1024e did you intend to `/submit` this Pull Request?

**Comment by whyc1125** [comment]
But i dunno what can i doJohannes Schindelin <notifications@github.com> 於 2020年11月6日 20:01 寫道：
@LifeIsStrange it's off topic all right. And a much better venue to discuss it would be the Git mailing list (send plain-text messages, HTML messages are dropped silently). You will find that you get the most useful feedback if you carefully craft a mail that contains all information necessary to understand your request, with links that do not need to be followed to understand the context.
@pi1024e did you intend to /submit this Pull Request?

**Comment by pi1024e** [comment]
@dscho I did indeed!

**Comment by dscho** [comment]
> @dscho I did indeed!

I ask because I didn't see you do it... Only when you add a comment that reads exactly `/submit` does GitGitGadget send the patches to the Git mailing list, and only the owner of the Pull Request can do it.

**Pull request closed without merging**
