### PR TITLE
git-stash: Don't GPG sign when stashing changes

### PR DESCRIPTION
**Pull request by cwc**
This is helpful for folks with commit.gpgsign = true in their .gitconfig.

### CODE REVIEW

**Comment by submitgit** [comment]
@cwc sent this commit (https://github.com/git/git/compare/2c78628255b8cc7f0b5d47981acea138db8716d2...2a267be70d152b5f629588a77ee60ec4d23e12d1) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/00000150dddb0eeb-b77240fb-1b63-4676-ac4b-1220b8d011ca-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=00000150dddb0eeb-b77240fb-1b63-4676-ac4b-1220b8d011ca-000000@eu-west-1.amazonses.com) [](00000150dddb0eeb-b77240fb-1b63-4676-ac4b-1220b8d011ca-000000@eu-west-1.amazonses.com)

**Comment by daurnimator** [comment]
Patch works for me.

**Comment by dustymabe** [comment]
seems to work for me too.

**Comment by daurnimator** [comment]
This can be closed now. `commit-tree` no longer signs by default.
See 2.9 release notes: https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L19-L23

**Pull request closed without merging**
