### PR TITLE
doc: list filter-branch subdirectory-filter first

### PR DESCRIPTION
**Pull request by glasser**
The docs claim that filters are applied in the listed order, so
subdirectory-filter should come first.

### CODE REVIEW

**Comment by submitgit** [comment]
@glasser sent this commit (https://github.com/git/git/compare/4010f1d1b782eb7585e0e0abcefa794bd5ff29a0...c15b27cd6ba2c6f7aef3409a5545a0906e4092a5) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015f277a12fe-c69362e3-b14c-4b5c-abaa-4693fd6632c2-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015f277a12fe-c69362e3-b14c-4b5c-abaa-4693fd6632c2-000000@eu-west-1.amazonses.com) [](0102015f277a12fe-c69362e3-b14c-4b5c-abaa-4693fd6632c2-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@glasser sent this commit (https://github.com/git/git/compare/4010f1d1b782eb7585e0e0abcefa794bd5ff29a0...9da87231905913e9e33b30bbe92b54037a6b30ca) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015f29b9128b-a8d6e31c-06f5-421c-989a-230a484482d3-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015f29b9128b-a8d6e31c-06f5-421c-989a-230a484482d3-000000@eu-west-1.amazonses.com) [](0102015f29b9128b-a8d6e31c-06f5-421c-989a-230a484482d3-000000@eu-west-1.amazonses.com)

**Comment by ShaneConsult** [comment]
Thanks so much

Regards 
Shane

**Comment by dscho** [comment]
This was integrated into `master` via e336afdfb67384aa058eeb47687545f0492ed40c

**Pull request closed without merging**
