### PR TITLE
Git commit verbose

### PR DESCRIPTION
**Pull request by pranitbauva1997**

### CODE REVIEW

**Comment by submitgit** [comment]
@pranitbauva1997 sent these 3 commits (https://github.com/git/git/compare/7e4ba3686ab04b2fdcb80f52e8784c9bebdb0401...bb2a9d2b6d10d7f94dd5cda99943b9a55391cdf4) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/01020153a7ba4e07-f326395b-63df-4f8a-b378-8f387b02d0bd-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=01020153a7ba4e07-f326395b-63df-4f8a-b378-8f387b02d0bd-000000@eu-west-1.amazonses.com) [](01020153a7ba4e07-f326395b-63df-4f8a-b378-8f387b02d0bd-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@pranitbauva1997 sent these 3 commits (https://github.com/git/git/compare/56331f8727b0c2e7dc713b728eaf1e5843422cb7...0edcb67cad2a2e50b7cdc2f842245e065ef50250) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/01020153b478cf07-758c7f14-33a1-4a67-9bc9-4688de3d6742-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=01020153b478cf07-758c7f14-33a1-4a67-9bc9-4688de3d6742-000000@eu-west-1.amazonses.com) [](01020153b478cf07-758c7f14-33a1-4a67-9bc9-4688de3d6742-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@pranitbauva1997 sent these 4 commits (https://github.com/git/git/compare/90f7b16b3adc78d4bbabbd426fb69aa78c714f71...edfee34b288291eb26cfb18a1e95ebd954dd35aa) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/01020153cd2340f8-4665cd5f-cd5c-41ab-a162-20acc43ca52e-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=01020153cd2340f8-4665cd5f-cd5c-41ab-a162-20acc43ca52e-000000@eu-west-1.amazonses.com) [](01020153cd2340f8-4665cd5f-cd5c-41ab-a162-20acc43ca52e-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@pranitbauva1997 sent these 5 commits (https://github.com/git/git/compare/90f7b16b3adc78d4bbabbd426fb69aa78c714f71...66c252caa9a7cac436f868f008ff0d8e2c25f1ec) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [Gmane](http://mid.gmane.org/01020153d952bd99-d3812bd6-d189-4780-ab48-f015696e9cf0-000000@eu-west-1.amazonses.com), [MARC](http://marc.info/?i=01020153d952bd99-d3812bd6-d189-4780-ab48-f015696e9cf0-000000@eu-west-1.amazonses.com) [](01020153d952bd99-d3812bd6-d189-4780-ab48-f015696e9cf0-000000@eu-west-1.amazonses.com)

**Comment by LestaD** [comment]
@pranitbauva1997 Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements. This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements.

**Comment by pranitbauva1997** [comment]
@LestaD Thanks for your advice. FYI, there exists a something called as [SubmitGit](http://submitgit.herokuapp.com/) which can be used to send PR's as patches and its also clear from the previous conversations. Thanks for your contribution.

**Pull request closed without merging**
