### PR TITLE
abspath.h file is generated by makeheaders tool

### PR DESCRIPTION
**Pull request by skrab-sah**
1. we don't need to commit the file.
2. added routin for abspath.c in Makefile.

cc: Taylor Blau <me@ttaylorr.com>

### CODE REVIEW

**Comment by webstech** [comment]
> Commit not signed off

Please specify `--signoff` on the commit command.

**Comment by skrab-sah** [comment]
> > Commit not signed off
> 
> Please specify `--signoff` on the commit command.

thanks.

**Comment by dscho** [comment]
> > > Commit not signed off
> > 
> > 
> > Please specify `--signoff` on the commit command.
> 
> thanks.

@skrab-sah and please remember to force-push without opening a new PR.

**Comment by skrab-sah** [comment]
OK

**Pull request closed without merging**
