### PR TITLE
t3433: new rebase testcase documenting a stat-dirty-like failure

### PR DESCRIPTION
**Pull request by newren**
Changes since v3:
  - add another patch which fixes the bug.  Thanks to Phillip for doing some digging to find the bug wasn't in rebase but in git_merge_trees().

### CODE REVIEW

**Comment by saa18877433** [comment]
https://github.com/git/git/commit/68aa495b590d417e88562ab1e5da7d84d0531f21

في الاثنين، ١٧ فبراير ٢٠٢٠ ٧:١٣ م Elijah Newren <notifications@github.com>
كتب:

**Comment by newren** [comment]
Just going to ignore all the infrastructure failures; I'm only adding a testcase, so the build shouldn't possibly break.

**Comment by dscho** [comment]
I think you'll need to make use of the `SYMLINKS` prereq, as [the Windows and Visual Studio tests are not happy](https://dev.azure.com/git/git/_build/results?buildId=1739&view=ms.vss-test-web.build-test-results-tab&runId=1032446&resultId=102421&paneView=debug):

```
+ ln -s unrelated DS
ln: failed to create symbolic link 'DS': No such file or directory
error: last command exited with $?=1
```

**Comment by newren** [comment]
All the errors look like infrastructure flakes (failing to download various xenial images and whatnot), so I'm going to ignore them.  Importantly, the windows builds passed, which is what I needed tested, so...

**Comment by newren** [comment]
Only renamed the file, so I'm going to resubmit without waiting for the tests...

**Comment by cloudcalad** [comment]
Acceso


Facebook

**Pull request closed without merging**
