### PR TITLE
Fixing wrong number reference

### PR DESCRIPTION
**Pull request by fabioqcorreia**
The last example of git revert usage, master~5..master~2 is explained like from "fifth to third" last commits. Fixing to "sixth to third".

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by myseife** [comment]
Po

**Comment by dscho** [comment]
@fabioqcorreia Thank you for your contribution!

Please add your [sign-off](https://git-scm.com/docs/SubmittingPatches#dco), and then submit your patch either via [GitGitGadget](https://gitgitgadget.github.io/), [submitGit](https://submitgit.herokuapp.com/) or manually, [via email](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
@fabioqcorreia ping?

**Comment by fabioqcorreia** [comment]
Hi, I've sent it via e-mail, thanks!

**Pull request closed without merging**
