### PR TITLE
git

### PR DESCRIPTION
**Pull request by anthonyolow**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by redturtle79** [comment]
Wish this wasn't such a big ordeal to make a URL or anything work for that matter, to hard to navigate this page

**Comment by dscho** [comment]
Is this PR serious? Why would anyone want to merge `master` into `maint`? That does not make sense!

**Comment by dscho** [comment]
@peff I think we can close this bogus PR. Is there a way to restrict new PRs to be opened only on branches that the person opening the PR can push to?

**Comment by peff** [comment]
Yeah, this can definitely be closed.

I remember mentioning this issue to GitHub folks a while back, and they agreed it was something to look into, but I don't remember if anything ever happened. Are there more recent instances (i.e., is it possible this one predates fixes from the last 6 months)?

**Comment by dscho** [comment]
> Are there more recent instances

I only saw this here PR being [built by the Azure Pipeline](https://dev.azure.com/git/git/_build?definitionId=11) every time @gitster pushed to `master`, so I think we're good.

**Pull request closed without merging**
