### PR TITLE
[Enhancement] Improve internals / refactoring.

### PR DESCRIPTION
**Pull request by shahzadlone**
Changed to many non-modifying vars to ```consts``` and tried to save arithmetic cost where I could.

Sorry my coding OCD bothered me when I didn't see them being ```consts```.

### CODE REVIEW

**Comment by shahzadlone** [comment]
@submitgit Is there a reason clang build failed??

**Comment by submitgit** [comment]
@shahzadlone sent these 3 commits (https://github.com/git/git/compare/b5101f929789889c2e536d915698f58d5c5c6b7a...9ffacb4e6a8136f80646f572147bb640a1758627) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020168a8338064-b1c054c4-3e05-4825-b8dc-636d9c63dcfc-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020168a8338064-b1c054c4-3e05-4825-b8dc-636d9c63dcfc-000000@eu-west-1.amazonses.com) [](01020168a8338064-b1c054c4-3e05-4825-b8dc-636d9c63dcfc-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@shahzadlone sent this commit (https://github.com/git/git/compare/b5101f929789889c2e536d915698f58d5c5c6b7a...bad432ec4a4f58404498ccb32639fdfcfe7b2ec9) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020168ab79f642-10a06c5b-c3f7-441e-86f8-bff5e41ac834-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020168ab79f642-10a06c5b-c3f7-441e-86f8-bff5e41ac834-000000@eu-west-1.amazonses.com) [](01020168ab79f642-10a06c5b-c3f7-441e-86f8-bff5e41ac834-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@shahzadlone sent this commit (https://github.com/git/git/compare/b5101f929789889c2e536d915698f58d5c5c6b7a...0eaec20ab2cd48952cf889b2ecc377655a49730d) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020168b080030b-eb0a0634-f2b9-42ed-a3be-76995e7127eb-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020168b080030b-eb0a0634-f2b9-42ed-a3be-76995e7127eb-000000@eu-west-1.amazonses.com) [](01020168b080030b-eb0a0634-f2b9-42ed-a3be-76995e7127eb-000000@eu-west-1.amazonses.com)

**Comment by shahzadlone** [comment]
This was merged [https://github.com/git/git/commit/33de80b1d50773f79e380eff33b4fc5c8ae1dd25]

So closing. =)

**Pull request closed without merging**
