### PR TITLE
Documentation: fix typos for the reference in new-command.txt

### PR DESCRIPTION
**Pull request by kyagi**
api-builtin.txt no longer exists. This change should have been done at ec14d4ecb5507550e31ba0a0016eb83fcde48f3f

### CODE REVIEW

**Comment by submitgit** [comment]
@kyagi sent this commit (https://github.com/git/git/compare/7668cbc60578f99a4c048f8f8f38787930b8147b...13a7606e5f63cb48fae70eb93224deb534632fef) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015fa0c804c4-7dc9e5b3-e34e-45e2-b92f-3f4183406020-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015fa0c804c4-7dc9e5b3-e34e-45e2-b92f-3f4183406020-000000@eu-west-1.amazonses.com) [](0102015fa0c804c4-7dc9e5b3-e34e-45e2-b92f-3f4183406020-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@kyagi hi! (And thank you for your patience.)

It would seem that your contribution may have been overlooked, most likely because

1. it was not [signed off](https://git-scm.com/docs/SubmittingPatches#dco), and
2. its commit message left a bit to be desired.

With regards to the latter: the Git project usually insists on quite verbose commit messages that describe interesting information that is not readily deduced from reading the diff.

In your case, I would wager a guess that it would do wonders to add a paragraph that talks about how this document was introduced in 29ed5489af4e (Documentation: how to add a new command, 2012-11-26), that there was an `api-builtin.txt` back then, and how ec14d4ecb550 (builtin.h: take over documentation from api-builtin.txt, 2017-08-02) got rid of that file, moving all the information directly into `builtin.h`.

That would convince e.g. me that this is a good change to have.

**Comment by dscho** [comment]
@kyagi ping?

**Comment by kyagi** [comment]
@dscho hi! (And thank you for your response.)

You exactly got the point. I agree with your idea that a paragraph should be added to describe the document's history. I would appreciate if you could handle it accordingly. Thank you.

**Comment by dscho** [comment]
@kyagi Please understand that open source relies on contributors to be active, so that not too much work is dumped on a single person (or just a handful). I can help you, but I cannot do the work _for_ you.

If you are no longer interested in this PR, close it.

**Comment by kyagi** [comment]
@dscho Certainly. Then, let me make a new push to describe it. Thank you for your help. :-)

**Comment by dscho** [comment]
> Then, let me make a new push to describe it.

I look forward to seeing it!

**Comment by kyagi** [comment]
Sorry for the delay. New push is https://github.com/git/git/pull/647

**Comment by dscho** [comment]
Is #647 superseding this here PR? If so, please close the latter.

FWIW you could also update _this_ PR by force-pushing the branch. But since you already opened a new PR...

**Comment by dscho** [comment]
> Is #647 superseding this here PR? If so, please close the latter.

It would appear so. Here, I'll close it for you.

**Pull request closed without merging**
