### PR TITLE
run-command.c: add hint when hook is not executable

### PR DESCRIPTION
**Pull request by mdamien**

### CODE REVIEW

**Comment by submitgit** [comment]
@mdamien sent this commit (https://github.com/git/git/compare/8fb8a945bc2dea2bb04249213ad8dacffbfc604f...04cc4dc0af5ce6d963959a7c2d04dd550cd22b77) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015ee1e41f17-927a8da1-ac14-4399-8424-fee8a82c2b0a-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015ee1e41f17-927a8da1-ac14-4399-8424-fee8a82c2b0a-000000@eu-west-1.amazonses.com) [](0102015ee1e41f17-927a8da1-ac14-4399-8424-fee8a82c2b0a-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@mdamien sent this commit (https://github.com/git/git/compare/217f2767cbcb562872437eed4dec62e00846d90c...c2839230a06abd69e6c158a57b29598191e28ad4) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015eee503678-52126849-7580-4832-9d46-0f5ac7a52336-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015eee503678-52126849-7580-4832-9d46-0f5ac7a52336-000000@eu-west-1.amazonses.com) [](0102015eee503678-52126849-7580-4832-9d46-0f5ac7a52336-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@mdamien sent this commit (https://github.com/git/git/compare/217f2767cbcb562872437eed4dec62e00846d90c...64216235c7f991cc9d097d76d17af7a55da7c960) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015ef0ba0273-ed29c030-7cdc-4535-a411-6cc443bd5f43-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015ef0ba0273-ed29c030-7cdc-4535-a411-6cc443bd5f43-000000@eu-west-1.amazonses.com) [](0102015ef0ba0273-ed29c030-7cdc-4535-a411-6cc443bd5f43-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
This was applied as f805a00a396ee91599902cebe55620b2a4c813b9

**Pull request closed without merging**
