### PR TITLE
Directory traversal bugs

### PR DESCRIPTION
**Pull request by newren**
This series documents multiple fill_directory() bugs, and fixes the one that is new to 2.24.0 coming from en/clean-nested-with-ignored-topic, the rest having been around in versions of git going back up to a decade.  

Changes since v4:
  * added a comment with the rationale for allocating an extra len+1 bytes for the dirent.

Cc: blees@dcon.de, gitster@pobox.com, kyle@kyleam.com, sxlijin@gmail.com

### CODE REVIEW

**Comment by dscho** [comment]
From https://dev.azure.com/git/git/_build/results?buildId=1446&view=logs:

> ```
> [...]
> t3011-common-prefixes-and-directory-traversal.sh (Wstat: 256 Tests: 22 Failed: 5)
>   Failed tests:  2-3, 16, 18-19
>   Non-zero exit status: 1
> [...]
> +++ diff -u expect actual
> --- expect	2019-12-08 07:50:30.418978500 +0000
> +++ actual	2019-12-08 07:50:30.512011200 +0000
> @@ -6,6 +6,6 @@
>  an_untracked_dir/untracked
>  empty
>  expect
> -untracked_*/empty
>  untracked_dir/empty
>  untracked_repo/
> +"untracked_\357\200\252/empty"
> error: last command exited with $?=1
> not ok 2 - git ls-files -o shows the right entries
```

This looks like a filename `untracked_*` is used, but `*` is invalid on Windows (and the Cygwin/MSYS layer translates it automatically into a Unicode character in the "private page", which I believe you see in action here).

Maybe mark it with FUNNYNAMES or something?

**Comment by newren** [comment]
> This looks like a filename `untracked_*` is used, but `*` is invalid on Windows (and the Cygwin/MSYS layer translates it automatically into a Unicode character in the "private page", which I believe you see in action here).
> 
> Maybe mark it with FUNNYNAMES or something?
> ```

Thanks for the explanation and the tip, @dscho!

**Comment by newren** [comment]
(The Travis CI build failed with "couldn't find gcc-8", which clearly isn't a bug in any changes I made, so I'm ignoring that spurious error.)

**Comment by kyleam** [comment]
> CC: [blees@dcon.de](mailto:blees@dcon.de), [gitster@pobox.com](mailto:gitster@pobox.com), [kyle@kyleam.com](mailto:kyle@kyleam.com), [sxlijin@gmail.com](mailto:sxlijin@gmail.com)

Just a heads up: Assuming this line was supposed to trigger that list of addresses to be cc'd, I didn't receive the series despite being included above.  Looking at the message in public-inbox, it seems like none of the addresses are included aside from Junio's.

**Comment by dscho** [comment]
> > CC: [blees@dcon.de](mailto:blees@dcon.de), [gitster@pobox.com](mailto:gitster@pobox.com), [kyle@kyleam.com](mailto:kyle@kyleam.com), [sxlijin@gmail.com](mailto:sxlijin@gmail.com)
> 
> Just a heads up: Assuming this line was supposed to trigger that list of addresses to be cc'd, I didn't receive the series despite being included above. Looking at the message in public-inbox, it seems like none of the addresses are included aside from Junio's.

I think the reason is that the comparison is case-sensitive (`Cc` vs `CC`). I edited the description to use the case expected by GitGitGadget.

**Comment by newren** [comment]
> error: 'grep remote error:.*not our ref.*64ea4c133d59fa98e86a771eda009872d6ab2886$ err' didn't find a match in:
> fatal: git upload-pack: not our ref 64ea4c133d59fa98e86a771eda009872d6ab2886
> fatal: unable to write to remote: Broken pipe
> error: last command exited with $?=1
> not ok 79 - deny fetch unreachable SHA1, allowtipsha1inwant=true

I didn't touch upload-pack or fetch; looks like some spurious error to me, so I'm going to go ahead and submit.

**Comment by dscho** [comment]
> > error: 'grep remote error:.*not our ref.*64ea4c133d59fa98e86a771eda009872d6ab2886$ err' didn't find a match in:
> > fatal: git upload-pack: not our ref 64ea4c133d59fa98e86a771eda009872d6ab2886
> > fatal: unable to write to remote: Broken pipe
> > error: last command exited with $?=1
> > not ok 79 - deny fetch unreachable SHA1, allowtipsha1inwant=true
> 
> I didn't touch upload-pack or fetch; looks like some spurious error to me, so I'm going to go ahead and submit.

Yes, t5516 is _still_ flaky on macOS. Actually, it seems that there is a very real bug in there that triggers (rarely) on macOS and @szeder is on it.

**Comment by newren** [comment]
The osx-gcc, osx-clang, and travis (the macos piece) all failed at installing perforce, which is unrelated to my change.  I was able to run the tests separately on a different mac os system, and they passed, so I'm ignoring those failures.

**Pull request closed without merging**
