### PR TITLE
Reuse formatting logic from ref-filter in cat-file

### PR DESCRIPTION
**Pull request by telezhnaya**
Start reusing formatting logic from ref-filter in cat-file.
Final goal is to make all formatting and printing work in ref-filter.

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by submitgit** [comment]
@telezhnaya sent these 20 commits (https://github.com/git/git/compare/36438dc19dd2a305dddebd44bf7a65f1a220075b...4f916e006000c6f1d643acdeacf8922542226102) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020160db0679c9-799a0bc4-b6d1-43e2-ad3b-80be4e4c55e9-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020160db0679c9-799a0bc4-b6d1-43e2-ad3b-80be4e4c55e9-000000@eu-west-1.amazonses.com) [](01020160db0679c9-799a0bc4-b6d1-43e2-ad3b-80be4e4c55e9-000000@eu-west-1.amazonses.com)

**Comment by leilaniwebcreation** [comment]
Link

**Comment by leilaniwebcreation** [comment]
Integration

**Comment by submitgit** [comment]
@telezhnaya sent these 18 commits (https://github.com/git/git/compare/6366dd9000a3f67e47a30d94375a88dabc18ec6f...d05e0b1c203a1cf3a0ddb5264ce474ca30aa860f) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/01020160df6dc499-0e6d11ec-1dcd-4a71-997b-ea231f33fae4-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=01020160df6dc499-0e6d11ec-1dcd-4a71-997b-ea231f33fae4-000000@eu-west-1.amazonses.com) [](01020160df6dc499-0e6d11ec-1dcd-4a71-997b-ea231f33fae4-000000@eu-west-1.amazonses.com)

**Comment by telezhnaya** [comment]
Will make new pull request later, need to work more on it

**Pull request closed without merging**
