### PR TITLE
sequencer: avoid garbled merge machinery messages due to commit labels

### PR DESCRIPTION
**Pull request by newren**
Changes since v1:
  * Added Taylor's Reviewed-by, and Junio's Acked-by (I assume that's a fair translation of "Looks good", anyway; feel free to adjust when you apply otherwise).

### CODE REVIEW

**Comment by newren** [comment]
The t5500-fetch-pack.sh failure in vs-test-4 looks like a possibly flaky test to me; certainly my simple one-line string changes to sequencer could not have affected that area of the code.  @jonathantanmy: are the test results above at all useful to you in determining if that's a flake?

**Comment by No0Mercy** [comment]
https://lore.kernel.org/git/pull.828.git.git.1596654345718.gitgitgadget@gmail.com
Git config**halooshloosh5@gmail.com
https://lore.kernel.org/git/pull.828.git.git.1596654345718.gitgitgadget@gmail.com

**Pull request closed without merging**
