### PR TITLE
Implement new zdiff3 conflict style

### PR DESCRIPTION
**Pull request by newren**
Implement a zealous diff3, or "zdiff3".  This new mode is identical to ordinary diff3 except that it allows compaction of common lines between the two sides of history, if those common lines occur at the beginning or end of a conflict hunk.

Change since v4:
  * None; just resending because v3 wasn't picked up.

Changes since v3:
  * More fixes from Phillip.
  * Marked Phillip as the author of the first commit because he's written most the code now; gave myself a co-authored-by trailer on that commit.
  * Removed the RFC label since it's now passing our tests.

Changes since v2:
  * Included more fixes from Phillip, and a new testcase

Changes since v1:
  * Included fixes from Phillip (thanks!)
  * Added some testcases

cc: Jeff King <peff@peff.net>
cc: Elijah Newren <newren@gmail.com>
cc: Sergey Organov <sorganov@gmail.com>
cc: Johannes Sixt <j6t@kdbg.org>
cc: Phillip Wood <phillip.wood123@gmail.com>
cc: Bagas Sanjaya <bagasdotme@gmail.com>
cc: Eric Sunshine <sunshine@sunshineco.com>

### CODE REVIEW

**Comment by brycemg** [comment]
brycegerhardt1@gmail.com

**Comment by justyou2914** [comment]
Help or support

**Review by Bubbas-Wife — COMMENTED** [review]
I just got into all this and I find it awesome the things that you can do that I never had a clue before now. Lol man have I been Missing out on the fun excitement going on lol.

**Comment by Eradnavna** [comment]
I  have no access to this account anymore. Please stop email me. On Tue, 30 Nov 2021 at 01:17, gitgitgadget-git[bot] ***@***.***> wrote:
This patch series was integrated into seen via 19a6c5c.

?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Eradnavna** [comment]
I  have no access to this account anymore. Please stop email me. On Tue, 30 Nov 2021 at 00:27, gitgitgadget-git[bot] ***@***.***> wrote:
This patch series was integrated into seen via 1e77105.

?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
