### PR TITLE
reftable library

### PR DESCRIPTION
**Pull request by hanwen**
This splits the giant commit from https://github.com/gitgitgadget/git/pull/539 into a series of smaller commits, which build and have unittests.

Changes relative to last series: version 19 Apr 2021 (tip: b8729fe)

* drop EINVAL for broken refs.
* fix 2 UBSAN warnings. Thanks to Andrzej Hunt for reporting.
* make tests pass against master (use oidread)
* handle worktree/xx/refname refs.
* handle main-worktree/ref 

cc: Han-Wen Nienhuys <hanwen@google.com>
cc: Jeff King <peff@peff.net>
cc: Ramsay Jones <ramsay@ramsayjones.plus.com>
cc: Jonathan Nieder <jrnieder@gmail.com>
cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>
cc: Jonathan Tan <jonathantanmy@google.com>
cc: Josh Steadmon <steadmon@google.com>
cc: Emily Shaffer <emilyshaffer@google.com>
cc: Patrick Steinhardt <ps@pks.im>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Felipe Contreras <felipe.contreras@gmail.com>
cc: Derrick Stolee <stolee@gmail.com>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Han-Wen Nienhuys <hanwen@google.com>g 
cc: "brian m. carlson" <sandals@crustytoothpaste.net>

### CODE REVIEW

**Review by neyzo6226 — APPROVED** [review]

**Comment by 0567807045** [comment]
Thanks for sharing!   
  
  
  
  
  
    
  

  
  
>

**Comment by 0567807045** [comment]
Thanks, I'll check it out.   
  
  
  
  
  
    
  

  
  
>

**Comment by hanwen** [comment]
@gitster 

> What's the current status of this thing? Is anybody reviewing?

not that I know :-(

I thought we were supposed to use the mailing list?

**Pull request closed without merging**
