### PR TITLE
doc: fix form -> from typo

### PR DESCRIPTION
**Pull request by crislinu**

### CODE REVIEW

**Comment by dscho** [comment]
@crislinu I believe this is a correct patch. Please do at least add your [`Signed-off-by:` footer](https://git-scm.com/docs/SubmittingPatches#dco). How do you plan on submitting the patch? Via [SubmitGit](https://submitgit.herokuapp.com/)? Or via [GitGitGadget](https://gitgitgadget.github.io/)?

**Comment by dscho** [comment]
@crislinu ping?

**Comment by crislinu** [comment]
I've added the `Signed-off-by`, but I don't know how to submit the patch Via SubmitGit or via GitGitGadget.

Can it be made from here?

**Comment by dscho** [comment]
>  I don't know how to submit the patch Via SubmitGit or via GitGitGadget.
> 
> Can it be made from here?

Yes, you can use [submitGit](https://submitgit.herokuapp.com) from here.

To use [GitGitGadget](https://gitgitgadget.github.io) instead, you'd have to re-open the PR at https://github.com/gitgitgadget/git.

You could also [send the patch manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by submitgit** [comment]
@crislinu sent this commit (https://github.com/git/git/compare/b697d92f56511e804b8ba20ccbe7bdc85dc66810...c6da065a13d0d697160539d5fd802a962920fd9f) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102016b8d597569-c1f6cfdc-cb45-4428-8737-cb1bc30655d8-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102016b8d597569-c1f6cfdc-cb45-4428-8737-cb1bc30655d8-000000@eu-west-1.amazonses.com) [](0102016b8d597569-c1f6cfdc-cb45-4428-8737-cb1bc30655d8-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@crislinu hey, I think you set off a pretty valuable thread ;-) Did you see it?

**Comment by dscho** [comment]
> I think you set off a pretty valuable thread ;-) Did you see it?

@crislinu in case you missed it: https://public-inbox.org/git/CAN0heSraZh+j04qjeaVtS5bsNoE=Hf_FBU-kfcB+69BkZz+zHg@mail.gmail.com/

Seems you got a lot of help, now it is time to follow through.

**Comment by dscho** [comment]
@crislinu gentle ping?

**Comment by dscho** [comment]
Closing in favor of https://github.com/gitgitgadget/git/pull/384.

**Comment by dscho** [comment]
@KINGRANDOLPH why so confused?

**Pull request closed without merging**
