### PR TITLE
Simplified merge logic

### PR DESCRIPTION
**Pull request by pi1024e**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

So the logic for the merging is somewhat confusing. So I simplified it to be equivalent. I tested all my changes to ensure in practice they work.

The first thing I did was test out which branch would occur for every possible value of 

remoteheads->next | common->next | option_commit | Branch
-- | -- | -- | --
T | T | T | A
T | T | F | A
T | F | T | A
T | F | F | A
F | T | T | C
F | T | F | C
F | F | T | B
F | F | F | A
Using this truth table, I was able to deduce that if the second branch ran, the if statement for the first branch was false. Taking the inverse, it was then found many of the checks were redundant, so the if statement was rewritten to have each branch run under the same exact conditions, except each value is evaluated as little as possible.

I hope you can approve of this and show me how to send it.

Thank you.

### CODE REVIEW

**Comment by dscho** [comment]
Please make sure that your commit message focuses on answering the question "why?" more than on "how?", and that it wraps at <= 76 columns per line. It is a good idea to spend quite a bit of time crafting the commit message, the clearer it is, the more likely the patch will be integrated. It is not unheard of patches with a mere one-liner as commit message to be entirely ignored by all potential reviewers. You might want to look through the commit history of `builtin/merge.c` for inspiration as to what constitutes a good commit message (according to the Git mailing list). Also do make sure to add your [sign off](https://git-scm.com/docs/SubmittingPatches#sign-off).

Your patch changes _quite_ a bit of code, and I am not sure that the indentation style matches the existing code's. The latter needs to be fixed, the former needs to be explained in the commit message.

It does look like the PR description copied the welcome message, rather than removing it, and then continues with a table that could potentially be worked into a good commit message, _iff_ a ton of background information is added so that developers who are unfamiliar with the implementation details of the merge can still understand it. Essentially, make it as attractive for reviewers as you can.

Finally send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
> I hope you can approve of this and show me how to send it.

I [did](https://github.com/git/git/pull/648#issuecomment-533195532)... But there has not been any reaction to what I said. Maybe you missed this, @pi1024e?

**Comment by dscho** [comment]
@pi1024e gentle ping?

**Comment by pi1024e** [comment]
Hello

**Comment by pi1024e** [comment]
I have seen everything. Of course I sent a request and rebased so it works with the modern codebase. I apologize for being somewhat inactive

**Comment by dscho** [comment]
>  I sent a request

What do you mean?

**Comment by pi1024e** [comment]
I sent a pull request to the mailing list.

**Comment by dscho** [comment]
> I sent a pull request to the mailing list.

@pi1024e I don't see it: https://public-inbox.org/git/?q=%22simplified+logic%22 comes up with a few hits that are certainly not your patch contribution.

Even just searching for a semi-random line I picked from the diff comes up empty: https://public-inbox.org/git/?q=%22add_strategies%28pull_twohead%2C+DEFAULT_TWOHEAD%29%3B%22

Further, I cannot see how _any_ of the concerns that I mentioned earlier in this PR are addressed. Let me restate them here:

> Please make sure that your commit message focuses on answering the question "why?" more than on "how?", and that it wraps at <= 76 columns per line. It is a good idea to spend quite a bit of time crafting the commit message, the clearer it is, the more likely the patch will be integrated. It is not unheard of patches with a mere one-liner as commit message to be entirely ignored by all potential reviewers. You might want to look through the commit history of builtin/merge.c for inspiration as to what constitutes a good commit message (according to the Git mailing list). Also do make sure to add your sign off.
>
> Your patch changes quite a bit of code, and I am not sure that the indentation style matches the existing code's. The latter needs to be fixed, the former needs to be explained in the commit message.
>
> It does look like the PR description copied the welcome message, rather than removing it, and then continues with a table that could potentially be worked into a good commit message, iff a ton of background information is added so that developers who are unfamiliar with the implementation details of the merge can still understand it. Essentially, make it as attractive for reviewers as you can.

In addition to those concerns, I also realized just now that your patch uses spaces for indentation, which contradicts the coding style of Git, and quite possibly makes the diff look more complex than it probably is.

Finally, it seems that the code that tries to avoid extra indentation levels was changed to introduce that very extra indentation that the original code tried to avoid, see e.g. https://github.com/git/git/pull/648/commits/ec4055face097775ecc8dc453172e1ea40fe48ce#diff-f4fa44232b21b3dd086b4d3f55800c4dL1451-R1457.

If you _really_ want to change that, you will want to extract that change into its own commit, as it has nothing to do with simplifying logic...

**Comment by pi1024e** [comment]
I am going to close this and make a new PR after following your suggestion. Thank you!

**Comment by dscho** [comment]
> I am going to close this and make a new PR after following your suggestion.

I never suggested to close this PR and open a new one. I _always_ suggest to force-push instead, to keep the history close together. Always.

But I see that you already deleted your fork, so you cannot even re-open this here PR. Unfortunate. Most unfortunate.

**Pull request closed without merging**
