### PR TITLE
Documentation: fix linkgit reference

### PR DESCRIPTION
**Pull request by YehezkelShB**
cc: Patrick Steinhardt <ps@pks.im>

### CODE REVIEW

**Comment by YehezkelShB** [comment]
@dscho or @ikke, would appreciate your help to `/allow` me into the premitted user list. Thanks!

**Comment by dscho** [comment]
It would have been nice _not_ to add another PR, [as I had requested](https://github.com/git/git/pull/1705#issuecomment-2054191626).

**Comment by YehezkelShB** [comment]
@dscho
Sorry, I missed your comment on the other PR. Will not repeat the same mistake again. Thanks for your understanding

**Pull request closed without merging**
