### PR TITLE
clang-format: fix typo in comment for formatting binary operations.

### PR DESCRIPTION
**Pull request by aneelamr**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

cc: Taylor Blau <me@ttaylorr.com>

### CODE REVIEW

**Comment by aneelamr** [comment]
@Red54 I've just created my first PR, could you please /allow me?

**Comment by Red54** [comment]
> @Red54 I've just created my first PR, could you please /allow me?

I think you should squash commits and sign off.

**Comment by aneelamr** [comment]
> > @Red54 I've just created my first PR, could you please /allow me?
> 
> I think you should squash commits and sign off.

Hi @Red54, thanks. I squashed and added a sign off.

**Comment by Red54** [comment]
> > > @Red54 I've just created my first PR, could you please /allow me?
> > 
> > 
> > I think you should squash commits and sign off.
> 
> Hi @Red54, thanks. I squashed and added a sign off.

Well done, then you should update the description of this Pull Request.

**Comment by Red54** [comment]
@aneelamr I have to remind you that your new commit title exceeds the 50 characters soft limit.
https://git-scm.com/docs/git-commit#_discussion

**Comment by Red54** [comment]
Maybe you can consider changing it to ".clang-format: fix typo in comment"

**Pull request closed without merging**
