### PR TITLE
Attempt to clarify a blurry sentence.

### PR DESCRIPTION
**Pull request by lboclboc**
Signed-off-by: Lars Berntzon <lars.berntzon@cecilia-data.se>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
Isn't it "clarify"? I.e. without the "e"?

**Comment by lboclboc** [comment]
Yes, your text is clear.  I realize now I miss-read the line as if it was:
If `git push [<repository>]` without any `<refspec>` argument is set, to -update some ref at the destination with `<src>` with....
I mentally placed the comma there and then I could not get pass that. But the main problem I have I guess is that the line refers to <src> and <dst>, but those comes from the ref-spec, but the whole line is about when ref-spec is not specified so the placeholders <src> and <dst> are not valid.

**Review by ryujinxx — APPROVED** [review]

**Comment by dscho** [comment]
Is this still active?

**Comment by lboclboc** [comment]
I still think the current documentation is wrong and impossible to understand correctly but I don't know how to formulate it better so let's close it now and I'll try to reformulated it.

**Pull request closed without merging**
