### PR TITLE
t3434: mark successful test as such

### PR DESCRIPTION
**Pull request by newren**
t3434.3 was fixed a week ago, but no-one noticed.  Mark it as such.

### CODE REVIEW

**Comment by newren** [comment]
A change to one of the tests could not have caused a completely unrelated test in a different testsuite to fail, so that's either an infrastructure failure or a flaky test.

**Comment by dscho** [comment]
> This branch is now known as [`master`](https://github.com/gitster/git/commits/master).

🤣

**Comment by newren** [comment]
> > This branch is now known as [`master`](https://github.com/gitster/git/commits/master).

:laughing:

**Pull request closed without merging**
