### PR TITLE
git-gui: fix _gitworktree on windows

### PR DESCRIPTION
**Pull request by valtron**
When GIT_WORK_TREE is set wrong, [git can crash](https://public-inbox.org/git/CAFKRc7y_kpCGNORENUZ2qw_4qBwjjyaaDFxAEQa52fTryj+w7A@mail.gmail.com/t).

This patch changes git-gui.sh to consistently normalize _gitworktree with `cygpath --windows` when `is_Cygwin`.

### CODE REVIEW

**Comment by dscho** [comment]
I think this is a valuable change.

Please make sure that your commit message focuses on answering the question "why?" more than on "how?", and that it wraps at <= 76 columns per line. Also do make sure to add your [sign off](https://git-scm.com/docs/SubmittingPatches#dco).

Finally send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
@valtron gentle ping?

**Comment by valtron** [comment]
Unfortunately I don't remember anymore what problem this was solving (this was a long time ago) so answering "why" would be super hard :)

Were you also having a problem that this patch would have fixed? If so what were you trying to do? Maybe it'll jog my memory.

**Comment by dscho** [comment]
> Unfortunately I don't remember anymore what problem this was solving (this was a long time ago) so answering "why" would be super hard :)

Well, you [linked](https://github.com/git/git/pull/335#issue-109612036) to it: https://public-inbox.org/git/CAFKRc7y_kpCGNORENUZ2qw_4qBwjjyaaDFxAEQa52fTryj+w7A@mail.gmail.com/t/#u

Following that conversation for a while (which I really would have loved for _you_ to do it, this is your contribution, not mine), it seems that ce83eadd9a2c63db6263df91933da1b1b865d26a fixed the underlying problem.

Seeing that you are
- no longer experiencing the problem,
- don't recall the specifics, and
- have deleted the fork that would allow you to update this here PR in the first place,
I will just close the PR.

**Comment by valtron** [comment]
I'm sorry, I feel I should explain. There were two things going on:
1. git-gui wasn't normalizing paths (fixed by the PR)
2. a crashing state existed in git (fixed in the commit you linked), triggered by the above

I did re-read the thread, but in it I hadn't mentioned what I was trying to do that involved (1); the fix for (2) was irrelevant to our present discussion.

**Pull request closed without merging**
