### PR TITLE
sparse-checkout: avoid staging deletions of all files

### PR DESCRIPTION
**Pull request by newren**
Changes since v1:
  * Fixed the ls command for portability, using the construct Junio suggested

CC: warmsocks@gmail.com, stolee@gmail.com

### CODE REVIEW

**Comment by newren** [comment]
Cancelled?!?  Well, osx-clang passed, and one passing on that platform is good enough for me when the other dies for some unknown infrastructure reason.

**Comment by dscho** [comment]
> Cancelled?!? Well, osx-clang passed, and one passing on that platform is good enough for me when the other dies for some unknown infrastructure reason.

That's probably an internal problem with the agents.

**Pull request closed without merging**
