### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by peutch**

### CODE REVIEW

**Comment by peutch** [comment]
This is a small correction concerning a help message in French regarding 'git branch -h'.
Signed-off-by: Patrice Duroux <patrice.duroux@gmail.com>

**Comment by dscho** [comment]
@peutch welcome to the Git community! Please note that the translations are maintained elsewhere, according to [`po/README`](https://github.com/git/git/blob/v2.31.1/po/README): would you mind opening a PR at https://github.com/git-l10n/git-po/?

**Comment by king350023** [comment]
git

**Review by fossdd — APPROVED** [review]
important patch!

**Comment by dscho** [comment]
Obsoleted by https://github.com/git-l10n/git-po/pull/513

**Pull request closed without merging**
