### PR TITLE
Make test selection easier by specifying description substrings instead of just numeric counters

### PR DESCRIPTION
**Pull request by newren**
This patch series enables me to change

   ./t9999-my-test.sh --run=1-3,5,17,19

into

   ./t9999-my-test.sh --run=setup,rename,symlink

and have it pick out tests with "setup", "rename", or "symlink" in their description and run those.  Saves me a lot of time, especially since numbers for tests aren't readily accessible.  The easiest way for me to get the numbers corresponding to the tests I want to run, is to run all the tests and look at the output to match up the descriptions with their numbers -- thus defeating the point of selecting just a subset of the tests to run in the first place.

Changes since v5:
  - Update comment to match the code (selectors are now only split on commas, not on whitespace)

cc: Phillip Wood <phillip.wood123@gmail.com>
cc: Taylor Blau <me@ttaylorr.com>
cc: Elijah Newren <newren@gmail.com>
cc: Jeff King <peff@peff.net>
cc: Junio C Hamano <gitster@pobox.com>
cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>
cc: Andrei Rybak <rybak.a.v@gmail.com>

### CODE REVIEW

**Comment by newren** [comment]
Looks like CI is just automatically cancelling all runs and marking them failed, so I'm going to ignore it.  The basic testsuite passes locally and the change from the previous round is pretty small.  So...

**Comment by newren** [comment]
Not much I can do about cancelled tests.  The test failure is due to a flaky test; I'll send a separate email about it.  (Besides, there were no code or test changes between v2 and v3.)  So...

**Comment by dscho** [comment]
> The test failure is due to a flaky test; I'll send a separate email about it.

Excellent. I agree that just checking for `null` is flaky when the host name can contain that substring. Checking for `(null)` is most likely what that test needs to do instead.

**Pull request closed without merging**
