### PR TITLE
Update fetch-options.txt

### PR DESCRIPTION
**Pull request by n9**
Section reference changed to link (to match pull-fetch-param.txt).

### CODE REVIEW

**Comment by dscho** [comment]
@n9 this patch is still necessary, right? If so, please write a good commit message and add your [`Signed-off-by:` footer](https://git-scm.com/docs/SubmittingPatches#dco). Thanks!

**Comment by dscho** [comment]
@n9 ping?

**Comment by n9** [comment]
@dscho It's tiny docs change that I did from the GitHub UI. Feel free to "signed-off-by" yourself. (I would need to checkout the git repo, create a spamsink email somewhere, amend commit, force push the branch ... too bureaucracy for me:)

**Comment by dscho** [comment]
> Feel free to "signed-off-by" yourself.

No, that's not possible. I cannot certify that you are legally permitted to release your work into the public.

**Comment by n9** [comment]
@dscho I mean by you as author. If there is nothing like `cla-not-required`, for instance: 

> For example, trivial typo fixes usually don’t require a CLA. If no CLA is required, the pull request is labelled as cla-not-required and you’re done. [[net-core](https://devblogs.microsoft.com/dotnet/net-core-open-source-update/)]

**Comment by dscho** [comment]
The Git project does not require a CLA, it requires a sign off.

**Comment by n9** [comment]
Done.

**Comment by dscho** [comment]
Thanks.

Now, please change the commit message to the preferred format, e.g. "docs(fetch): use correct markup to refer to a section", and then use [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Pull request closed without merging**
