### PR TITLE
gitk: fix show_line_source from not-staged 'commit' when not in repo root

### PR DESCRIPTION
**Pull request by golvok**
PR for submitGit.

Will try to contact Paul first

### CODE REVIEW

**Comment by dscho** [comment]
> Will try to contact Paul first

Did you do so?

**Comment by golvok** [comment]
I talked to him shortly after I made this PR, we discussed it, and seemed to have settled on a commit message and patch. I just updated this PR to match it. He didn't give me a timeframe for merging it.

**Comment by dscho** [comment]
> I just updated this PR to match it. He didn't give me a timeframe for merging it.

AFAICT gitk is maintained at git://ozlabs.org/~paulus/gitk. I am not sure whether he requires you to send a patch to the Git mailing list, Cc:ing him (you could use submitGit or GitGitGadget for that), or whether you need to actually make a fork of the gitk repository (without the rest of Git's source code) to pull from.

@paulusmack care to clarify?

**Comment by dscho** [comment]
> care to clarify?

@paulusmack ?

**Comment by golvok** [comment]
Sorry, I must have forgotten about this conversation. In our discussion, he said that he prefers to receive patches to his email, and I sent it to him that way. He didn't mention the Git mailing list.

**Comment by dscho** [comment]
> he said that he prefers to receive patches to his email

Okay, then ;-)

**Comment by dscho** [comment]
So let's close this PR, as you took things to email.

**Pull request closed without merging**
