### PR TITLE
Detect linking style for HP aCC on HP-UX

### PR DESCRIPTION
**Pull request by michael-o**
HP aCC does not accept any of the previously tested formats, but only its own.
Add this one to configure.ac.

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
Maybe send this patch to the mailing list for review? You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by michael-o** [comment]
I actually did a month ago: https://public-inbox.org/git/3cabed9e-3949-93cc-2c9c-500a9cd9d4cd@siemens.com/T/#m786251f99d38f1a135cac7a0ded66e4ecd52d4a0

**Comment by dscho** [comment]
Ah, and to keep telling this story, we could also say that it continues here: https://github.com/cr-marcstevens/sha1collisiondetection/pull/50? And that the issue has been addressed in Git as of https://github.com/git/git/commit/4125f78222749cb8fc91115abec3ac83e5dfb194?

If so, we could theoretically close this PR, right?

**Comment by michael-o** [comment]
No, the patch contains two changes:

* Endianess for SHA1
* Linking style detection

The former has been merge, the latter has not.

**Comment by dscho** [comment]
> The former has been merge, the latter has not.

Oh, okay. Are you planning on giving the latter a "ping?" after v2.22.0 is out? (It's what I would suggest to do...)

**Comment by michael-o** [comment]
I didn't actually planned because after discussion/assessment I had the feeling that this change has been blessed by several committers.  I am not able to use `git send-email` because our corporate relay accepts corporate domains only.

**Comment by dscho** [comment]
> Shall I ping again?

I would, of course after v2.22.0 ;-) (the current plan is to release it the day after tomorrow, see https://tinyurl.com/gitCal)

**Comment by michael-o** [comment]
@dscho Done.

**Comment by dscho** [comment]
Worked, too, even if v2.22.0 is not quite out yet ;-)

**Comment by dscho** [comment]
This is now 9a1699c88eceaba695603511566727a4629284a1, right? If so, it is already in `next` and on its way into `master`.

**Comment by michael-o** [comment]
Indeed, here is the merge commit: https://github.com/git/git/commit/5add3b28b288254bb4f346594965390cdce6a4fc.

**Pull request closed without merging**
