### PR TITLE
Port to Plan 9

### PR DESCRIPTION
**Pull request by lufia**
I ported *git*, and git subcommands only written in C to Plan 9.
This pull request contains patches for existing codes, and new files to build *git* in Plan 9.

All build options such as *NO_PERL* are not supported yet.

Whole installing process is published at https://medium.com/@lufia/14fee2ad7493

------

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
Wow! Plan 9, eh? How's this effort going?

**Comment by lufia** [comment]
@dscho Thank you.
Git works well on my Plan 9 box.

After replying to reviews for other dependent libraries, such as LibreSSL, I will tidy this pull request and submit it to ML.

**Comment by lufia** [comment]
Continuation: gitgitgadget/git#305

**Comment by dscho** [comment]
> Continuation: [gitgitgadget#305](https://github.com/gitgitgadget/git/pull/305)

Why a new PR? You lose all of GitGitGadget's convenience like automatically generating the range-diff.

**Comment by lufia** [comment]
This PR is opened on git/git so I think it is used only for testing. Actual PR still be opened on gitgitgadget/git repo.

Is it correct? or is there better way?

**Comment by dscho** [comment]
> This PR is opened on git/git so I think it is used only for testing.

These days, you can `/submit` directly from git/git.

**Pull request closed without merging**
