### PR TITLE
doc: add missing space to git-status man page

### PR DESCRIPTION
**Pull request by adrian5**
I doubt my commit has the right format, but I'm sure you can forward a fix yourself. Thanks.

### CODE REVIEW

**Comment by adrian5** [comment]
@dscho If this has been fixed (or forwarded), close this PR. No use making it linger.

**Comment by dscho** [comment]
@adrian5 the ball is still in your court... Have you seen [this](https://github.com/git/git/pull/945#issuecomment-761813144)?

> Invalid author email in [68dbbe5](https://github.com/git/git/commit/68dbbe5629f090e150548ccaad18dd2665ee93da): "[adrian5@users.noreply.github.com](mailto:adrian5@users.noreply.github.com)"

The Git project requires you to use your real name and email address for your contributions. Yes, even small contributions.

You can fix this by setting `user.name` and `user.email` appropriately, and then calling `git commit --amend --reset-author`. Then force-push. (Yes, you will have to clone your repository and check out `patch-1` to do that.)

While you do that, please also rebase your patch (`git fetch https://github.com/git/git master && git rebase FETCH_HEAD`). That way, you will have a chance to resolve the merge conflicts.

Finally, once you force-push and GitGitGadget does not complain, and there are no merge conflicts, it is time to `/submit`.

**Comment by adrian5** [comment]
If you see my original comment, I just wanted to notify of a missing space, not have my own PR merged. If there was a "feedback" button (or an issue tracker) I would have used that. I have no intent of switching to a public email address, nor get inolved with mailing lists. So if someone could simply file a patch themselves, then it's solved.

**Comment by dscho** [comment]
> a "feedback" button

As per https://git-scm.com/community, that would be the Git mailing list.

**Comment by adrian5** [comment]
Yes, I am aware. My original intent was for this PR to function as feedback. I'll close this PR now, it looks have become [redundant](https://github.com/git/git/commit/1b5b8cf072491e0a43e668c685b782efce9a6f0f) in the meantime.

**Pull request closed without merging**
