### PR TITLE
change 'commands' to comments and improve wording

### PR DESCRIPTION
**Pull request by talkbox6**

### CODE REVIEW

**Comment by submitgit** [comment]
@Solder-Soldier sent this commit (https://github.com/git/git/compare/b06d3643105c8758ed019125a4399cb7efdcce2c...860e91566e952ce7b471223ea4be43d4ff81d009) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015c4809f8c7-a5cb604c-782d-4a10-87e1-2fe23e9989ba-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015c4809f8c7-a5cb604c-782d-4a10-87e1-2fe23e9989ba-000000@eu-west-1.amazonses.com) [](0102015c4809f8c7-a5cb604c-782d-4a10-87e1-2fe23e9989ba-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
@talkbox6 have you seen this reply by the Git maintainer himself? https://public-inbox.org/git/xmqq8tlga2yz.fsf@gitster.mtv.corp.google.com/

Please do respond.

**Comment by talkbox6** [comment]
@dscho yeah i did see that. I may finish the submission if I have time

**Comment by dscho** [comment]
> if I have time

If you find out that you don't, please close this PR.

**Pull request closed without merging**
