### PR TITLE
Correction in the translation file fr.po

### PR DESCRIPTION
**Pull request by cellebrek**
uptream -> upstream in help comment

### CODE REVIEW

**Comment by karenetheridge** [comment]
"This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements."

**Comment by louy2** [comment]
You can also try https://submitgit.herokuapp.com/

**Comment by dscho** [comment]
@cellebrek Please rebase your PR, and then open a PR either in the indicated fork or in https://github.com/git-l10n/git-po.

**Comment by dscho** [comment]
@cellebrek please rebase and open a new PR over at https://github.com/git-l10n/git-po. Thank you.

**Pull request closed without merging**
