### PR TITLE
userdiff.c: Added support for record types in C#

### PR DESCRIPTION
**Pull request by 304NotModified**
Support for C# 9 records. See https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/records

I will try to use GitGitGadget

### CODE REVIEW

**Comment by 304NotModified** [comment]
> Invalid author email in [f1d6bd0](https://github.com/git/git/commit/f1d6bd07d9ecdd2bd14f0937c40580e2a6998250): "[304NotModified@users.noreply.github.com](mailto:304NotModified@users.noreply.github.com)"

Close because of this

**Comment by dscho** [comment]
> 
> 
> > Invalid author email in [f1d6bd0](https://github.com/git/git/commit/f1d6bd07d9ecdd2bd14f0937c40580e2a6998250): "[304NotModified@users.noreply.github.com](mailto:304NotModified@users.noreply.github.com)"
> 
> Close because of this

The easiest fix would be to clone this locally, fix your `user.name` and `user.email` setting, then `git commit --amend --reset-author` and force-push. And then of course reopen this PR.

**Comment by 304NotModified** [comment]
Yes thanks, except I don't have any email addresses that are for public usage.

**Comment by dscho** [comment]
> Yes thanks, except I don't have any email addresses that are for public usage.

A public email address is necessary to communicate with the reviewers on the Git mailing list. The idea is that you can be contacted in case questions arise around your patch in the future, as you are considered the domain expert on your contribution.

**Comment by 304NotModified** [comment]
cannot reopen this one, so will create a new PR

image

**Pull request closed without merging**
