### PR TITLE
fix: prevent date underflow when using positive timezone offset

### PR DESCRIPTION
**Pull request by dxrcy**
cc: Patrick Steinhardt <ps@pks.im>
cc: Phillip Wood <phillip.wood123@gmail.com>
cc: darcy <acednes@gmail.com>
cc: Jeff King <peff@peff.net>
cc: <rsbecker@nexbridge.com>
cc: Karthik Nayak <karthik.188@gmail.com>
cc: Eric Sunshine <sunshine@sunshineco.com>

### CODE REVIEW

**Comment by dxrcy** [comment]
Hey @dscho, sorry to bother you, but how should I best add the `Signed-off-by` trailer to the commit ? I don't want to force anything or rebase, if it will mess with the GitGadget process :-)

**Comment by dxrcy** [comment]
> The best way is to make sure that your `user.name` and `user.email` are configured correctly, then call `git commit --amend -s` and force-push.

Thanks for the quick reply :-) should be good now.

**Comment by dscho** [comment]
> > The best way is to make sure that your `user.name` and `user.email` are configured correctly, then call `git commit --amend -s` and force-push.
> 
> Thanks for the quick reply :-) should be good now.

Yup, that worked.

**Comment by Lizzyrobin4** [comment]
Helo

**Pull request closed without merging**
