### PR TITLE
replace test -f with test_path_is_file

### PR DESCRIPTION
**Pull request by krush11**
Although  has the same functionality as test_path_is_file(), in
the case where test_path_is_file() fails, we get much better debugging
information.

Replace  with test_path_is_file so that future developers
will have a better experience debugging these test cases.

### CODE REVIEW

**Comment by dscho** [comment]
@krush11 you need to sign off using your real name (see https://git-scm.com/docs/SubmittingPatches#sign-off):

> Also notice that a real name is used in the `Signed-off-by` trailer. Please don’t hide your real name.

**Comment by krush11** [comment]
@dscho are there any further changes required before this is ready for merge?

**Comment by dscho** [comment]
> 
> 
> @dscho are there any further changes required before this is ready for merge?

Looks good to me! Time to `/submit`.

**Comment by dscho** [comment]
If you keep deleting your fork, you won't be able to submit new revisions of the patch series, frustrating everyone. Maybe keep your fork open until the patch series is merged into `master`, addressing feedback and providing new iterations every couple of days as needed?

**Comment by krush11** [comment]
sry my bad, I am new to the contributing styles of git. Will try to avoid deletions from now on.

**Comment by dscho** [comment]
> 
> 
> sry my bad, I am new to the contributing styles of git. Will try to avoid deletions from now on.

To be clear, this has nothing to do with contributing to Git per se. If you delete your fork, _any_ PR associated with a branch in that fork will be closed. That goes for every fork you have, no matter which project.

**Pull request closed without merging**
