### PR TITLE
2.15.0.txt: fixed a typo

### PR DESCRIPTION
**Pull request by eli-b**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by submitgit** [comment]
@eli-b sent this commit (https://github.com/git/git/compare/cb5918aa0d50f50e83787f65c2ddc3dcb10159fe...064a798301ab238976562c4da24bc5d27bb75605) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015f6d5221d7-eb6c29ae-2c92-41e5-b7e1-735c88fd1e89-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015f6d5221d7-eb6c29ae-2c92-41e5-b7e1-735c88fd1e89-000000@eu-west-1.amazonses.com) [](0102015f6d5221d7-eb6c29ae-2c92-41e5-b7e1-735c88fd1e89-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
This patch was most likely ignored because it lacked a [sign off](https://git-scm.com/docs/SubmittingPatches#dco). In any case, the typo has been fixed in 8684dde10d482550afa9a2fb5df07171185c2b88.

**Comment by eli-b** [comment]
Thanks for your attention.
I suggest a tag be automatically added to patches that lack a sign off so they don't seem to just be waiting forever.

**Comment by dscho** [comment]
> I suggest a tag be automatically added to patches that lack a sign off so they don't seem to just be waiting forever.

If you are volunteering ;-)

**Pull request closed without merging**
