### PR TITLE
Next

### PR DESCRIPTION
**Pull request by chucherko**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
@peff do you agree that this obviously bogus PR can be closed?

**Comment by peff** [comment]
@dscho Yeah, I closed this and the others you pointed to. I admit I un-`watch`ed git/git PRs a while ago because they were mostly spam anyway, so I hadn't noticed these ones.

**Comment by dscho** [comment]
@peff would you trust me with closing what I consider obviously invalid PRs?

**Comment by peff** [comment]
@dscho Definitely. There's a new "triage" permission in GitHub which would give you that ability but without having full write access (not that I particularly distrust you with write access, but as a general principle I'd like to minimize write access to the git/git repo). But it's part of a beta that we don't seem to be enrolled in. I'm looking into it.

**Comment by dscho** [comment]
@peff well, you did give me write permission some time ago, and I promised never to abuse it. I still stand by my word.

**Comment by peff** [comment]
@dscho Yeah, I was just realizing that. So yes, please close PRs as you see fit. Possibly we should revisit your permission later (and I wish I could reduce mine, but there's not yet a way to still do admin stuff without being able to push to the repo :wink), but it's not urgent.

**Comment by dscho** [comment]
Okay. Phew. There are still way too many open PRs for my liking, but I have to stop for now ;-)

**Pull request closed without merging**
