### PR TITLE
completion: bash: fix late declaration of `__git_cmd_idx`

### PR DESCRIPTION
**Pull request by fab4100**

### CODE REVIEW

**Comment by dscho** [comment]
@fab4100 could I trouble you to edit the [PR description](https://github.com/git/git/pull/1038#issue-672961875) so that it does not repeat the commit message? I ask for this because the PR description will be copied into the mail that will be sent to the Git mailing list, after the commit message (duplicating it if you don't edit the description), between the `---` line and the diffstat.

**Comment by dscho** [comment]
Right, I forgot to mention: if you want to see how it will look like, use the `/preview` command.

**Comment by phil-blain** [comment]
Note for lurkers and GitHub spelunkers: this patch was sent manually to the list at https://lore.kernel.org/git/20210618140256.256481-1-fabianw@mavt.ethz.ch/ and merged in https://github.com/git/git/commit/a38c4c02e536b772526ad236b9887e28dab1d1e1 which made it to Git 2.33.0

**Pull request closed without merging**
