### PR TITLE
Documentation/SubmittingPatches: Correct a few typographical errors

### PR DESCRIPTION
**Pull request by WillDereham**
A few typographical changes, including:

  - Add missing quotes (line 84)
  - Remove some double spaces
  - Improve some line wrapping
  - Make bullet lists consistent (i.e. "." to "-")

### CODE REVIEW

**Comment by dscho** [comment]
As you can see in the document touched by this PR, the Git project expects code contributions to be sent as patches to the mailing list...

In the meantime, merge conflicts crept in. Could you please rebase onto `master`, make sure that your commit message does not repeat what can be readily seen in the patch, and add your [sign off](https://git-scm.com/docs/SubmittingPatches#dco)?

Finally send the patch to the mailing list for review. You can use [GitGitGadget](https://gitgitgadget.github.io), [submitGit](https://submitgit.herokuapp.com) or [send it manually](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#submit-your-patch).

**Comment by dscho** [comment]
@WillDereham gentle ping?

**Comment by dscho** [comment]
@WillDereham gentle ping?

**Comment by WillDereham** [comment]
@dscho Please stop messaging me. I have no intention to simbit this 2 year old patch to the project, and I don't appreciate the follow up messages. If you really want these changes implemented, go do it yourself. I also don't appreciate the tone in which you are expecting me to do this, without any consideration for the fact that I have a busy life, and I don't have time to chase up pull requests from 2 years ago. I appreciate you are just doing your job, but please stop bothering people.

**Comment by dscho** [comment]
@WillDereham it would have been enough to simply close this PR.

**Pull request closed without merging**
