### PR TITLE
explain the order of output in cat-file batch operations since it is not explicit

### PR DESCRIPTION
**Pull request by ahmedakef**
cc: Patrick Steinhardt <ps@pks.im>

### CODE REVIEW

**Comment by dscho** [comment]
@ahmedakef you will want to review the guidelines, in particular [the part about signing off on patches](https://git-scm.com/docs/SubmittingPatches#dco): The Git project is very unyielding on that requirement.

**Comment by ahmedakef** [comment]
preview

**Comment by ahmedakef** [comment]
@dscho  @pks-t  when I edited my commit message and force push the PR was closed, can you open it again?

**Comment by dscho** [comment]
@ahmedakef I fear that something went utterly wrong:

image

And indeed, the commit you pushed is now a root commit (i.e. it has no parent commits): https://github.com/git/git/commit/94fa04ad4fed8e3b6a04f0e879169514eb9e8b6b

To fix it, you will need to rebase it onto upstream's `master` branch, force-push and _then_ reopen.

**Comment by ahmedakef** [comment]
I tried rebase but also failed, opened a new one here: https://github.com/git/git/pull/1768

**Comment by dscho** [comment]
@ahmedakef does not look like you failed, but now that you opened the other PR, this here PR cannot be reopened any longer:

image

The problem with opening new PRs is that the history (and the range-diff between iterations) will be lost, which makes reviewing harder than necessary.

**Comment by ahmedakef** [comment]
@dscho I agree, sorry for inconvenience and thank you for help
I tried rebase and push but couldn't reopen it either, I will be more careful the next time

**Pull request closed without merging**
