### PR TITLE
Fix D/F issues in stash

### PR DESCRIPTION
**Pull request by newren**
This series fixes a few D/F issues in the stash command.  These were some issues I found while working on unintentional removal of untracked files/directories and the current working directory, and I'm just submitting them separately.

Changes since v1:
  * Fix accidental creation of file named 'expect' (copy-paste problem...)
  * Documented the reason for adding is_path_a_directory() and not using is_directory()
  * Removed typo, fixed up confusing wording, and added a companion test to show that F->D and D->F have the same fix.

cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>
cc: Derrick Stolee <stolee@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
@newren sorry for the long wait, my fault: I left the build agent in the middle of some maintenance. It's all working again now.

**Comment by newren** [comment]
@dscho: No worries; I went to sleep and figured it'd either be resolved by the time I woke up or I'd email you to find out what was up.  Glad to see it was the former.  :-)

**Pull request closed without merging**
