### PR TITLE
[DO NOT MERGE YET] Speed up interactive rebase

### PR DESCRIPTION
**Pull request by dscho**
This is still-experimental work to finally start to get rid of the cumbersome shell script implementation of the interactive rebase.

This PR serves mainly as a checkpoint for CI.

### CODE REVIEW

**Comment by petervanderdoes** [comment]
As stated in the description of this repository:
##### Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements.

Please close this PR

**Comment by dscho** [comment]
@petervanderdoes I am very familiar with Git's submission process, but thanks for trying to help.

> Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored. Please follow Documentation/SubmittingPatches procedure for any of your improvements.

This description is incorrect. If you want to use the submitGit method of submitting patches to the Git mailing list (which is a convenient way for contributors who are uncomfortable with mail-based patch submissions), they *have* to open a PR here.

Besides, as I mentioned, the idea of this here PR is to benefit from the testing performed by Travis.

So no, I will not close this ticket.

**Comment by dscho** [comment]
@petervanderdoes I hope you see how useful it is to keep this PR open?

**Comment by rumpelsepp** [comment]
> This description is incorrect. If you want to use the submitGit method of submitting patches to the Git mailing list (which is a convenient way for contributors who are uncomfortable with mail-based patch submissions), they have to open a PR here.

Maybe the description could be updated by someone?

**Comment by dscho** [comment]
> > This description is incorrect. If you want to use the submitGit method of submitting patches to the Git mailing list (which is a convenient way for contributors who are uncomfortable with mail-based patch submissions), they have to open a PR here.
> 
> Maybe the description could be updated by someone?

Someone already submitted a patch (so that the hint is actually correct: Documentation/SubmittingPatches would then describe the submitGit-based flow, too): http://git.661346.n2.nabble.com/PATCH-1-2-Partition-SubmittingPatches-doc-into-two-files-tt7653295.html

The best course of action would be to chime in and help.

**Comment by rumpelsepp** [comment]
I did mean that particular snippet at the github repository description: 
> Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored.

I think that this causes confusion, since pull request are appearently useful (submit git, travis, ...). I would suggest that you just replace the text with a link to the [SubmittingPatches documentation](https://github.com/git/git/blob/master/Documentation/SubmittingPatches) instead.

**Comment by peff** [comment]
I can change the repo description, but I was waiting for the updates to SubmittingPatches (linked by @dscho above) to be merged (we haven't seen updates there, which I'm guessing is simply because @rtyley has been busy).

We _can_ update the description in the meantime, but I thought @gitster's point was interesting: do we actually need PRs for submitGit, or would it make sense for it to be able to send directly from a branch in your own fork? That would reduce the amount of pointless notifications one gets from watching the git/git repo. But it may have downsides, or be complicated technically. I don't know.

**Comment by rsy140588** [comment]
Dear Sir ,

i dont need to git please dont any email to me.

thanks .....

**Comment by peff** [comment]
@rsy140588 If you don't want to receive notifications, you can follow the link at the bottom of the email, and "unwatch" the git/git repository at the top of the page (you may still get notifications for ongoing threads unless you also "unsubscribe" from the right-hand toolbar of the individual threads).

**Comment by dscho** [comment]
> I did mean that particular snippet at the github repository description:
> 
>     Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored.
> 
> I think that this causes confusion, since pull request are appearently useful (submit git, travis, ...). I would suggest that you just replace the text with a link to the SubmittingPatches documentation instead.

But it *is correct* that Pull Requests are ignored!!! If you want to submit patches, you *got* to study the file mentioned in the blurb. It *just so happens* that one way (that is still being developed) is to use submitGit, which *just so happens* to require bogus Pull Requests.

So I do not see how changing the blurb according to your wishes would clarify things. To the contrary, I would expect * a lot more confusion* by developers who open Pull Requests and then get frustrated because nothing happens.

Does that make sense?

**Comment by dscho** [comment]
> We can update the description in the meantime, but I thought @gitster's point was interesting: do we actually need PRs for submitGit, or would it make sense for it to be able to send directly from a branch in your own fork? That would reduce the amount of pointless notifications one gets from watching the git/git repo. But it may have downsides,

The most obvious downside for me is: I like that Travis tests my code (although it seems to have had problems with MacOSX with my most recent update: it failed, without any logs, leading me to believe that the problem is on Travis' side; I will find out with my next update).

**Comment by gitster** [comment]
@dscho, you'd need to clarify what "chiming in and help" means over there. The patches got review comment and then stalled - the author can revise as suggested, or push back with a counter-argument. Either way, the ball is still in author's court and there aren't much others can help by merely "chiming in".

http://thread.gmane.org/gmane.comp.version-control.git/291569

**Comment by peff** [comment]
@dscho Good point. In theory people can run Travis directly against branches in their forks, but there's a non-zero setup cost for them (AFAIK), as opposed to just visiting the Travis page and seeing that the tests have already been run.

**Comment by dscho** [comment]
@gitster understood. But even preparing a patch incorporating the feedback, and sending it back to the mailing list ready for @rtyley to sign off, would be more helpful that chatting in this here PR, as much fun as it is.

Speaking of too much talking: I need to get back to the rebase--helper patches.

**Pull request closed without merging**
