### PR TITLE
branch: add new copy branch feature

### PR DESCRIPTION
**Pull request by sahildua2305**
Working on this new feature for supporting copying a branch (just like
renaming) including its config section.

Signed-off-by: Sahil Dua <sahildua2305@gmail.com>

### CODE REVIEW

**Comment by submitgit** [comment]
@sahildua2305 sent this commit (https://github.com/git/git/compare/1eb437020a2c098a7c12da4c05082fbea10d98c9...56c025170802a488d64280ec3953fb3d636def33) as a patch to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015c5146c8ca-e5144538-326b-47b8-8c81-af31da4cdfe0-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015c5146c8ca-e5144538-326b-47b8-8c81-af31da4cdfe0-000000@eu-west-1.amazonses.com) [](0102015c5146c8ca-e5144538-326b-47b8-8c81-af31da4cdfe0-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@sahildua2305 sent these 6 commits (https://github.com/git/git/compare/0339965c70d68fd3831c9a5306443c869de3f6a8...b056972a33ccbc63d05029a5cd4c5a35c3f4eacd) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015c60dcf5f6-057de56f-3355-40dc-a0d3-ee62fa9b8259-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015c60dcf5f6-057de56f-3355-40dc-a0d3-ee62fa9b8259-000000@eu-west-1.amazonses.com) [](0102015c60dcf5f6-057de56f-3355-40dc-a0d3-ee62fa9b8259-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@sahildua2305 sent these 3 commits (https://github.com/git/git/compare/0339965c70d68fd3831c9a5306443c869de3f6a8...77ecc5e988e74f78dfa15c98aedfc8359fb47fd8) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015c64f0dceb-02338e52-74d5-4d6c-9a9d-f41e98ff88bc-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015c64f0dceb-02338e52-74d5-4d6c-9a9d-f41e98ff88bc-000000@eu-west-1.amazonses.com) [](0102015c64f0dceb-02338e52-74d5-4d6c-9a9d-f41e98ff88bc-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@sahildua2305 sent these 3 commits (https://github.com/git/git/compare/69e6b9b4f4a91ce90f2c38ed2fa89686f8aff44f...87e17cbe5f38f9618944db0574c6fc7581b467a4) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015c79fcbda0-2779b4ff-54ad-46f4-bef0-14eeb58338d4-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015c79fcbda0-2779b4ff-54ad-46f4-bef0-14eeb58338d4-000000@eu-west-1.amazonses.com) [](0102015c79fcbda0-2779b4ff-54ad-46f4-bef0-14eeb58338d4-000000@eu-west-1.amazonses.com)

**Comment by submitgit** [comment]
@sahildua2305 sent these 3 commits (https://github.com/git/git/compare/41dd4330a1210003bd702ec4a9301ed68e60864d...e128a7285d82885ebe583645e979a874483ac7dd) as a set of patches to the mailing list with [_submitGit_](https://github.com/rtyley/submitgit) - here on [public-inbox](https://public-inbox.org/git/0102015ca23f0488-7423db93-b65f-4214-8221-af6a1bb4c2e5-000000@eu-west-1.amazonses.com/), [MARC](http://marc.info/?i=0102015ca23f0488-7423db93-b65f-4214-8221-af6a1bb4c2e5-000000@eu-west-1.amazonses.com) [](0102015ca23f0488-7423db93-b65f-4214-8221-af6a1bb4c2e5-000000@eu-west-1.amazonses.com)

**Comment by dscho** [comment]
Integrated via 3b48045c6c73

**Pull request closed without merging**
